Random Names from Team
YARC-Official/YARG pull request #257
Opened 2023-05-06 04:57 UTC by nevespt

[EDITED]
- Added a function to read from Credits.txt and add a random name for the "Empty" Player Name
- Change the "BOT" text to blue color

[CHANGED]
- Changed Location of Credits.txt from '/Assets' to '/Assets/Resources'

2023-05-06 15:39 UTC, EliteAsian123 requested changes
Thanks for your PR, it's appreciated as always! Please look at review comments, and then I can merge.

2023-05-06 15:39 UTC, EliteAsian123 commented on Assets/Script/PlayerManager.cs
> +		public struct randomName {
Please follow C# naming conventions (should be `RandomName`)

2023-05-07 02:33 UTC, nevespt commented on Assets/Script/PlayerManager.cs
> +		public struct randomName {
all good now, thanks for the naming guideline <3

2023-05-07 02:35 UTC, nevespt commented
ig its all good now, sorry about the naming

2023-05-07 17:54 UTC, EliteAsian123 approved these changes

2023-05-07 17:54 UTC, merged