Added Song Preview to Music Library
YARC-Official/YARG pull request #324
Opened 2023-05-14 04:58 UTC by JayDiddyThaGOAT

- Configured 30s preview duration & shorter fade-in time
- Added Preview Volume Button to Settings (25% by default)
- Added max volume parameter to FadeIn function
- Made FadeOut function a UniTask that runs until all playing stems are fully muted
- Disable crowd stem when previewing audio from ini file
- Added functions for start & stopping preview audio (with looping mechanic at Start function)

TODO in Future: Disable crowd stem when previewing audio from con file

2023-05-14 14:42 UTC, EliteAsian123 requested changes

2023-05-14 14:42 UTC, EliteAsian123 commented on Assets/Script/Audio/Bass/BassAudioManager.cs
> +				while (true) {
`_exitPreviewLoop` is not cancelled when switching songs, which means that this loops continues to go on. Because `StartPreviewAudio` is being repeatedly called, many instances of this loop are being created, which causes a memory leak, and eventually a crash or hang.

2023-05-14 14:42 UTC, EliteAsian123 commented on Assets/Script/Audio/Bass/BassStemMixer.cs
> +				{
Formatting

2023-05-14 14:46 UTC, JayDiddyThaGOAT commented on Assets/Script/Audio/Bass/BassStemMixer.cs
> +				{
Fixed in def52f1

2023-05-14 21:28 UTC, JayDiddyThaGOAT commented
Sorry this is blocked atm. Found the game-breaking bug that loops the song while in Play Mode

2023-05-14 23:55 UTC, JayDiddyThaGOAT commented
Reopened the PR. The looping bug is fixed now in 4c4ce0b

2023-05-15 19:58 UTC, EliteAsian123 commented
Unfortunately, my first review comment is not fixed. `StartPreviewAudio` is repeatedly called, and `_exitPreviewLoop` is never cancelled. This makes the loops go on forever, until the song select is exited.

2023-05-16 02:11 UTC, JayDiddyThaGOAT commented
Got it fixed this time. I made sure the LoopPreviewAudio task appears once in the UniTask tracker. 

https://github.com/YARC-Official/YARG/assets/25489150/893335d1-0350-4434-8de6-d7e15f7aa487

2023-05-16 20:39 UTC, EliteAsian123 approved these changes

2023-05-16 20:39 UTC, merged