Headers are added for the different sections, merged results, filter for songs without certain instruments
YARC-Official/YARG pull request #460
Opened 2023-06-12 05:51 UTC by SamuelPalma

+ Headers are only shown if the song list is greater than 30 songs (arbritrary number)
    + TODO: Tweak constant MIN_SONGS_FOR_SECTION_HEADERS

* Added filters to search for songs without a specific instrument + instrument:-guitar + instrument:-bass + instrument:-drums + instrument:-keys + instrument:-vocals + instrument:-band

* The search results are merged + source:rb1dlc;source:rb2dlc

* Fixed bug that displayed the following filter incorrectly if the back button was pressed

* SongSelection.cs class refactored + SongSearching.cs created

2023-06-12 05:58 UTC, SamuelPalma commented
Filters for songs without a specific instrument

![YARG_20230611_235706](https://github.com/YARC-Official/YARG/assets/47540469/8558c29b-994b-4c41-9d26-7f201cb34f7c)

2023-06-12 06:04 UTC, SamuelPalma commented
Merged results
![YARG_20230612_000213](https://github.com/YARC-Official/YARG/assets/47540469/33b5e7d0-1420-4040-9b6c-8ee9fffb9cdd)

2023-06-12 06:07 UTC, SamuelPalma commented
Section headers
![YARG_20230612_000601](https://github.com/YARC-Official/YARG/assets/47540469/c70fbbbf-bf1e-4862-9883-a89eb75e6146)

2023-06-12 18:00 UTC, SamuelPalma commented
Hello, the current implementation of the headers is a button without associated functionality [ButtonViewType](https://github.com/YARC-Official/YARG/blob/master/Assets/Script/UI/MusicLibrary/ViewTypes/ButtonViewType.cs) that is inserted in the appropriate place. 

Apparently the [CategoryViewType](https://github.com/YARC-Official/YARG/blob/master/Assets/Script/UI/MusicLibrary/ViewTypes/CategoryViewType.cs) class already has a section for counting, but we would have to modify the way in which the songs are added, to add them by section step by step and not globally.


Regarding the subheadings we would have to create a new class that extends [ViewType](https://github.com/YARC-Official/YARG/blob/master/Assets/Script/UI/MusicLibrary/ViewTypes/ViewType.cs) that contains a list of [SongViewType](https://github.com/YARC-Official/YARG/blob/master/Assets/Script/UI/MusicLibrary/ViewTypes/SongViewType.cs), but I believe that it is possible.

2023-06-13 19:38 UTC, EliteAsian123 requested changes

2023-06-13 19:38 UTC, EliteAsian123 commented on Assets/Script/Song/SongSearching.cs
> +		private readonly static List<Tuple<string, string>> troublesomeCharacters = new List<Tuple<string, string>>{
`List<Tuple<string, string>>` can be simplified to `List<(string, string)>`, or better yet, `List<(string from, string to)>`.

2023-06-14 19:38 UTC, EliteAsian123 approved these changes

2023-06-14 19:38 UTC, merged