Small refactor around loading a song entry's audio
YARC-Official/YARG pull request #521
Opened 2023-07-08 04:50 UTC by sonicfind

+ Simplify the stem channel inheritance hierarchy a bit
+ Split the ExConSongEntry stem map into the separate stems - allows easier stem type-base audio removal when specified on audio load.
+ Move MoggInfoGeneration function into the ConEntry class directly

2023-07-08 21:45 UTC, RileyTheFox requested changes
Mostly happy with the changes, I just think that ExConSongEntry is extremely bloated now as the purpose of the SongEntry classes were for storing song info to play the song or to cache it

2023-07-08 21:45 UTC, RileyTheFox commented on Assets/Script/Audio/Bass/BassMoggStemChannel.cs
> +        readonly public float left;
Proper formatting is access modifiers first, then field modifiers

2023-07-08 21:45 UTC, RileyTheFox commented on Assets/Script/Audio/Bass/BassStemMixer.cs
> +            return !_channels.ContainsKey(stem) ? EMPTYCHANNELLIST : _channels[stem];
Use Array.Empty<T> here, it's cleaner than a static list. Internal is also redundant here as internal only restricts usage to an assembly, not per file/class

2023-07-08 21:45 UTC, RileyTheFox commented on Assets/Script/Song/Types/ExConSongEntry.cs
> +        public void SetAudioValues(DataArray dta, List<DataArray> dta_update_roots = null)
Really not a fan of this. It bloats the song entry class when it is mostly intended to be used for storing fields related to caching. This class is just extremely huge now and it doesn't need to be. I'd recommend putting this elsewhere.

2023-07-08 21:45 UTC, RileyTheFox commented on Assets/Script/Song/Types/ExConSongEntry.cs
> +        public void SetAudioValues(DataArray dta, List<DataArray> dta_update_roots = null)
The LoadAudio functions are fine however

2023-07-08 21:45 UTC, RileyTheFox commented on Assets/Script/Song/Scanning/SongScanThread.cs
> +                currentSong.SetAudioValues(currentArray.Array("song"), updateValue);
I kind of preferred the old system for this because the ExConSongEntry is just extremely bloated now

2023-07-09 08:15 UTC, sonicfind commented on Assets/Script/Song/Types/ExConSongEntry.cs
> +        public void SetAudioValues(DataArray dta, List<DataArray> dta_update_roots = null)
To be fair, this isn’t exactly how I want to it be like to start with. However, how I want to work would require completely redoing our current DTA loading system entirely. I’m fine with reverting to the generator for now (though it’s 3am, so that’ll have to wait, lol)

2023-07-09 13:48 UTC, sonicfind commented on Assets/Script/Audio/Bass/BassMoggStemChannel.cs
> +        readonly public float left;
Idk how I did that

2023-07-09 18:09 UTC, RileyTheFox approved these changes

2023-07-09 18:10 UTC, merged