Add audio preview file support
YARC-Official/YARG pull request #531
Opened 2023-07-23 16:15 UTC by sonicfind

2023-07-23 19:56 UTC, EliteAsian123 requested changes

2023-07-23 19:56 UTC, EliteAsian123 commented on Assets/Script/Audio/PreviewContext.cs
> +                bool usesPreviewFile = await song.LoadPreviewAudio(_manager, 1f);
Awaiting this would do nothing because none of the overrides are asynchronous. Consider changing return type to just `bool`, or use `UniTask.RunOnThreadPool` within the overrides.

2023-07-24 01:09 UTC, sonicfind commented
*burp*

2023-07-25 17:03 UTC, EliteAsian123 approved these changes

2023-07-25 17:03 UTC, merged