New Object for the Menu Badges
YARC-Official/YARG pull request #537
Opened 2023-08-11 02:47 UTC by nevespt

[Added] 
- Badge Backgroud in white (to change colors)
- Badge Prefab
- Badge Script
  - Set text to Bage
  - Set Color to Background and Text

[Changed]
- Menu Entry Prefab (Replaced the old static badges to the New ones)
- Main Menu Prefab resulted of changing the Menu Entry Prefab

2023-08-11 02:53 UTC, EliteAsian123 requested changes

2023-08-11 02:53 UTC, EliteAsian123 commented on Assets/Script/Menu/BadgeMenu.cs
> +        private RawImage BadgeImgComponent;
Private serialized fields should be `_likeThis` not `LikeThis`.

2023-08-11 02:53 UTC, EliteAsian123 commented on Assets/Script/Menu/BadgeMenu.cs
> +
Remove empty line

2023-08-11 02:53 UTC, EliteAsian123 commented on Assets/Script/Menu/BadgeMenu.cs
> +                Graphic badgeGraphic = BadgeImgComponent.GetComponent<Graphic>();
`var` instead of `Graphic`

2023-08-11 02:53 UTC, EliteAsian123 commented on Assets/Script/Menu/BadgeMenu.cs
> +            }
Lines 49-61 and 31-43 can probably be consolidated into a method to simplify code

2023-08-11 02:53 UTC, EliteAsian123 commented
Thanks for the PR! Please apply feedback before I can approve.

2023-08-12 15:26 UTC, nevespt commented
@EliteAsian123 Rev.1 added

2023-08-12 16:21 UTC, EliteAsian123 approved these changes

2023-08-12 16:40 UTC, EliteAsian123 commented
Merged in 450687f

2023-08-12 16:40 UTC, closed without merging