Open Replay Folder in Replay Menu
YARC-Official/YARG pull request #562
Opened 2023-09-11 06:29 UTC by nevespt

2023-09-11 19:58 UTC, EliteAsian123 requested changes

2023-09-11 19:58 UTC, EliteAsian123 commented on Assets/Script/Replays/ReplayContainer.cs
> +            System.Diagnostics.Process.Start(ReplayDirectory);
Please use `FileExplorerHelper.OpenFolder` instead, as this does not work on all platforms.

2023-09-11 19:58 UTC, EliteAsian123 commented on Assets/Script/Settings/Customization/CustomContentManager.cs
> +            System.Diagnostics.Process.Start(CustomizationDirectory);
This is unused.

2023-09-11 19:58 UTC, EliteAsian123 commented on Assets/Script/Menu/Replays/ReplaysMenu.cs
> +                new NavigationScheme.Entry(MenuAction.Select, "Open Folder", () => ReplayContainer.OpenReplayDirectory()),
This should also probably be a UI button on the header (similar to the “Add Profile”) button on the profiles menu. I'll merge this PR without it, but that might make this better.

2023-09-12 08:23 UTC, nevespt commented on Assets/Script/Menu/Replays/ReplaysMenu.cs
> +                new NavigationScheme.Entry(MenuAction.Select, "Open Folder", () => ReplayContainer.OpenReplayDirectory()),
we can ask Kadu about the ui

2023-09-12 08:29 UTC, nevespt commented
@EliteAsian123 this should work now, i hope

2023-09-18 02:21 UTC, EliteAsian123 approved these changes

2023-09-18 02:21 UTC, EliteAsian123 commented
Sorry for the wait!

2023-09-18 02:21 UTC, merged