Stagekit implementation
YARC-Official/YARG pull request #579
Opened 2023-10-11 03:28 UTC by TheFatBastid

This is a port of the old engine code, not a re-write, so I welcome people to check it out to see if there are better ways to do things that I do not have knowledge of.

2023-10-11 15:10 UTC, EliteAsian123 commented on Assets/Script/Venue/StageKit/StageKitGameplay.cs
> +        public static StageKitGameplay Instance { get; private set; }
Static instance variables on `GameplayBehaviour` types (classes that only exist at play time) are no longer recommended. It's now advised to have an instance of the variable in `GameManager` instead. [See `PracticeManager` as an example](https://github.com/YARC-Official/YARG/blob/19adab6d630a49469aefc991b18eeb1b4bb1b938/Assets/Script/Gameplay/GameManager.cs#L114).

2023-10-11 15:11 UTC, EliteAsian123 commented on Assets/Script/Venue/StageKit/StageKitGameplay.cs
> +    public class StageKitGameplay :  GameplayBehaviour
It's probably a good idea to format these files (there are a couple formatting inconsistencies such as the double space here).

2023-10-11 15:14 UTC, EliteAsian123 commented on Assets/Script/Venue/StageKit/StageKitLightingController.cs
> +        public static StageKitLightingController Instance { get; private set; }
Assuming this call is present in the persistent scene, this is fine, however, the `MonoSingleton` class should be used instead. [See `DiscordController` as an example](https://github.com/YARC-Official/YARG/blob/19adab6d630a49469aefc991b18eeb1b4bb1b938/Assets/Script/Integration/DiscordController.cs#L11).

2023-10-11 15:15 UTC, EliteAsian123 commented on Assets/Script/Venue/StageKit/StageKitLightingController.cs
> +                    case 0:
Consider using an enum here instead of just using 0, 1, 2, 3, 4... etc.

2023-10-11 18:45 UTC, RileyTheFox requested changes

2023-10-11 18:45 UTC, RileyTheFox commented on Assets/Script/Venue/StageKit/StageKitLighting.Parents.cs
> +            StageKitGameplay.Instance.gameManger.BeatEventManager.Unsubscribe(OnBeat);
GameManager should almost never be a publicly accessible instance to another class.

2023-10-11 18:45 UTC, RileyTheFox commented on Assets/Script/Venue/StageKit/StageKitGameplay.cs
> +        public static StageKitGameplay Instance { get; private set; }
Public variables should be named using PascalCase. For example largeVenue should be LargeVenue. I also recommend sorting fields the fields in a class so that public fields are above private fields. Easier to find what you're looking for if you know the accessor (which is denoted by the underscore in a _privateField or such as PublicField)

2023-10-11 18:45 UTC, RileyTheFox commented on Assets/Script/Venue/StageKit/StageKitLightingController.cs
> +        public StrobeSpeed previousStrobeState = StrobeSpeed.Off;
All these fields should be PascalCase

2023-10-11 18:45 UTC, RileyTheFox commented on Assets/Script/Venue/StageKit/StageKitLightingController.cs
> +        private readonly Queue<(int, byte)> _commandQueue = new();
I suggest naming the tuple variables here so its easy to understand what they do.

You can do Queue<(int anInt, byte aByte)>, and then the tuple will have named fields.

2023-10-11 18:45 UTC, RileyTheFox commented on Assets/Script/Venue/StageKit/StageKitLightingController.cs
> +                switch (curCommand.Item1)
Refer to my comment regarding the _commandQueue tuple, naming the fields of the tuple will make it more descriptive than `Item1` and `Item2`.

2023-10-18 22:54 UTC, EliteAsian123 reviewed
I made some quick comments below; no action necessary. I'll make a proper review when I'm home (yes I did this on mobile).

2023-10-18 22:54 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitGameplay.cs
> +            //Is there a OnPause/OnResume event? that would simplify this.
No, but you can just modify the pause method to call a method within this class. If that's too much work though, leaving it like this is fine.

2023-10-18 22:54 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitScore.cs
> +        private void KillCue() //The only cue used on the score screen is timed, no need to have all the action and token stuff here.
It may be beneficial to make this a method of `_controller`.

2023-10-19 19:55 UTC, EliteAsian123 requested changes
Hey, I did a few more comments. It's probably a good idea to just auto-format all of these files, and disregard all of the formatting reviews. After that, it should be good! Thanks!

Also, your branch is outdated (from both YARG and YARG.Core). It's probably a good idea to update them, so I can merge without conflicts!

2023-10-19 19:55 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitGameplay.cs
> +namespace YARG
The namespace should match the folder: `YARG.Integration.StageKit`

2023-10-19 19:55 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitLighting.Primitives.cs
> +	internal class BeatPattern : StageKitLighting
Since everything is in the same assembly, `internal` has no effect compared to `public` here, and can probably be replaced with `public`.

2023-10-19 19:55 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitLighting.Cues.cs
> +            var patternList1 = new List<(int, byte)>
Since these are (I believe) never added to after their creation, you can convert these into arrays instead of lists. You can then optimize it by only creating the array once and providing the same array:
```cs
private static readonly (int, byte)[] PATTERN_1 =
{
  (RED, ALL),
  (RED, NONE),
  (RED, NONE),
  (RED, NONE),
};

public BigRockEnding()
{
  // ...

  CuePrimitives.Add(new BeatPattern(PATTERN_1, true, 8.0f));

  // ...
}
```
This can be repeated for all cues.

2023-10-19 19:55 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitLighting.Cues.cs
> +    internal class LoopCool : StageKitLightingCue
(Formatting) put empty lines between classes

2023-10-19 19:55 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitLighting.Cues.cs
> +	internal class ManualCool : StageKitLightingCue{
Formatting (`{`)

2023-10-19 19:55 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitLighting.Cues.cs
> +			} ;
Formatting (space before `;`). It's probably a good idea to just let Rider format this file.

2023-10-20 20:44 UTC, closed without merging