Tweaked implementation
YARC-Official/YARG pull request #585
Opened 2023-10-22 01:57 UTC by TheFatBastid

Files now formatted by Rider, wow!

2023-10-23 22:58 UTC, EliteAsian123 requested changes
Hello, last review, I promise. After all of these things are addressed, we should be good to go! We just gotta wait for #584 to be merged, and this PR updated for that, and I can merge this ASAP in time for the next alpha. Thanks again for your hard work!

2023-10-23 22:58 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitLightingController.cs
> +                { 0x00, 0x00, 0x00, 0x00 }; //this is only for the SendCommands() command to limit swamping the kit.
Try to avoid comments on the end of lines because you'll get some weird wrapping like this.

2023-10-23 22:58 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitLightingController.cs
> +                0.001f; //necessary to prevent the stage kit from getting overwhelmed and dropping commands. In seconds. 0.001 is the minimum. Preliminary testing indicated that 7ms was needed to pre
Same here

2023-10-23 22:58 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitLightingController.cs
> +                InputDeviceChange change) // Listen for new stage kits being added or removed at any time.
And here

2023-10-23 22:58 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitLightingController.cs
> +                    0.05f / SEND_DELAY) //If there is more 1/20th of a second in commands left in the queue when the cue changes, clear it. Really fast songs can build up a queue in the thousands whi
And here. Should be like this instead. Try to keep characters on the left of the gray line:
![image](https://github.com/YARC-Official/YARG/assets/29520859/53b79a6f-9a2a-47b9-a7ea-ae14aedba915)

2023-10-23 22:58 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitLightingController.cs
> +        public enum StrobeSpeed
Can this just be removed and replaced with the `StageKitStrobeSpeed` type instead? It would simplify the `SetStrobeSpeed` method for example.

2023-10-23 22:58 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitGameplay.cs
> +        public event Action<double> HandleVocals;
Making these events is very inefficient, as you're constantly doing `+=` and `-=` on them (all yellow lines are new allocations).
![image](https://github.com/YARC-Official/YARG/assets/29520859/49940309-6aab-40da-b120-cd389d78733f)

Instead, you should make these methods. See comment below as to how.

2023-10-23 22:58 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitGameplay.cs
> +            HandleVocals += _controller.CurrentLightingCue.HandleVocalEvent;
This can be easily converted to, for example:
```cs
private void HandleBeatline() {
  if (_controller.CurrentLightingCue == null) return;

  _controller.CurrentLightingCue.HandleBeatlineEvent();

  foreach (var primitive in _controller.CurrentLightingCue.CuePrimitives) {
    primitive.HandleBeatlineEvent();
  }
}
```
or something since the `CurrentLightingCue` is set above.

2023-10-23 22:58 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitGameplay.cs
> +            GameManager.BeatEventManager.Unsubscribe(primitive.OnBeat);
The `KillPrimitive` method can be removed after the refactor above, however, when is the `primitive.OnBeat` subscribed? It isn't above. Unless it is in the constructor? If so, a comment should be put here to state that.

2023-10-23 22:58 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitGameplay.cs
> +
After the refactor, all of this event stuff can be removed.

2023-10-23 22:58 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitGameplay.cs
> +            //On Pause, turn off the fog and strobe so people don't die, but leave the leds on, looks nice.
This whole update method is large, which is fine, but is running in whole if there's no stage kits attached. It may be a good idea to skip it all if there's nothing attached.

2023-10-23 22:58 UTC, EliteAsian123 commented on Assets/Scenes/PersistentScene.unity
The "Stage Kit Lighting Controller" component should be moved to the "Integrations" object to make things more consistent.

2023-10-24 00:34 UTC, TheFatBastid commented on Assets/Script/Integration/StageKit/StageKitLightingController.cs
> +                    0.05f / SEND_DELAY) //If there is more 1/20th of a second in commands left in the queue when the cue changes, clear it. Really fast songs can build up a queue in the thousands whi
TIL of the gray line

2023-10-24 01:17 UTC, TheFatBastid commented on Assets/Script/Integration/StageKit/StageKitLightingController.cs
> +        public enum StrobeSpeed
Can't remember why I did that in the old code. Not needed and removed.

2023-10-24 02:59 UTC, TheFatBastid commented
Okay changes made. Waiting for #584. Review and comments always welcome!

2023-10-27 21:08 UTC, EliteAsian123 approved these changes

2023-10-27 21:08 UTC, merged