Auto-generate venue lighting incase it doesn't exist
YARC-Official/YARG pull request #588
Opened 2023-11-03 22:04 UTC by raphaelgoulart

This code reads a JSON file containing info on which lighting presets/post-procs to use for which sections, and generates a lighting track based on that info, if the song currently being loaded doesn't have it.
Implementation loosely based on MagmaC3's, detailed in http://docs.c3universe.com/rbndocs/index.php?title=Venue_Autogeneration
This needs implementation on the YARG side as well, but the game should still behave the same without it (i.e. songs loading normally, without venue autogeneration).

Example auto-generation preset JSON file, for testing purposes: [DefaultPreset.json](https://github.com/YARC-Official/YARG.Core/files/13253806/DefaultPreset.json)
Demo video: https://www.youtube.com/watch?v=jd588FNhSOE (for any `[next]` counter that resets to 0 for no reason -- that's the blend-in lighting event, not a `[first]` keyframe)

TODO:
- Figure out better way to organize the lookup dictionaries;
- Implement selection in Settings screen. Implementation suggestion:
  - Have built-in presets in some game folder, like `StreamingAssets/autogen` or similar;
  - Read custom presets from `PersistentDataPath/autogen` or similar;
  - List them in a dropdown in the settings, either near to other venue-related settings, or on the Presets tab;
  - Pass the selected preset as a parameter for the Song.LoadChart() function.
- (Very low priority) Add singalong events based on HARM2 phrases if any (add to the first two performers that are available in this order: guitar/bass/keys/drums)

2023-11-08 23:06 UTC, EliteAsian123 requested changes
Hi thanks for the PR! Mostly everything is pretty good, however there are a few things with the serialization I recommended.

As for styling, if you could, please separate blocks of code with empty lines. For example, the `GenerateLightingEvents` is just one big block of code and is kinda hard to look through. Thanks!

2023-11-08 23:06 UTC, EliteAsian123 commented on Assets/Script/Venue/Lights/VenueAutogenerationPreset.cs
> +            AutogenerationSectionPreset sectionPreset = new AutogenerationSectionPreset();
Instead of doing all of this, I'd highly recommend serializing into the `AutogenerationSectionPreset` instead using `JsonConvert.DeserializeObject<AutogenerationSectionPreset>(<text>)` instead. In fact, you can make it *even easier* on yourself by making a class like this:
```cs
public class AutogenerationSectionFile {
   public string CameraPacing;
   public Dictionary<string, AutogenerationSectionPreset> SectionPresets;
}
```
and doing this on `ReadPresetFromFile`:
```cs
JsonConvert.DeserializeObject<AutogenerationSectionFile>(File.ReadAllText(path))
```

This has several pros:
* Type checking on everything automatically
* No need for string constants and stuff everywhere (bad practice)
* Code that is a lot easier to understand
* And also the `.json` fields will be in spec with YARG's preferred `.json` field naming (PascalCase)

Any value checking can be done after the fact by looking at the values of the output file.

2023-11-08 23:06 UTC, EliteAsian123 commented on Assets/Script/Venue/Lights/VenueAutogenerationPreset.cs
> +    }
Are these only used within the `VenueAutogenerationPreset` class? If so, they should be private and at the top and within the said class.

2023-11-08 23:06 UTC, EliteAsian123 commented on Assets/StreamingAssets/autogen/DefaultPreset.json
Placing default presets for this in StreamingAssets is fine, however other users putting things in here could be problematic because of how the YARC Launcher works (files here will be deleted).

2023-11-08 23:12 UTC, raphaelgoulart commented on Assets/StreamingAssets/autogen/DefaultPreset.json
Yeah, these are meant to be only default presets, customs should be placed elsewhere when I get to implementing it in settings

2023-11-08 23:12 UTC, raphaelgoulart commented on Assets/Script/Gameplay/HUD/LyricBar.cs
> +            lyricText = lyricText.Replace('§', ' ');
No, but it fixes a bug with the synalepha character showing as an unknown character. Fixed it on my end, guess I forgot to remove this from the commit.
If you want I can undo it

2023-11-08 23:25 UTC, raphaelgoulart commented on Assets/Script/Venue/Lights/VenueAutogenerationPreset.cs
> +            AutogenerationSectionPreset sectionPreset = new AutogenerationSectionPreset();
Thanks for the advice! I have zero familiarity with Newtonsoft.JSON so I knew my implementation had lots of room for improvement (to say the least lmao), this'll make my life easier for sure

2023-11-09 15:18 UTC, raphaelgoulart commented on Assets/Script/Venue/Lights/VenueAutogenerationPreset.cs
> +        }
Fixed in https://github.com/YARC-Official/YARG/pull/588/commits/c1e8058104ce2f0a7274b44b99dbe8e80091c8ca

2023-11-09 15:20 UTC, raphaelgoulart commented on Assets/Script/Venue/Lights/VenueAutogenerationPreset.cs
> +    }
Fixed in https://github.com/YARC-Official/YARG/pull/588/commits/c1e8058104ce2f0a7274b44b99dbe8e80091c8ca and https://github.com/YARC-Official/YARG/pull/588/commits/8e1200bb560f0db6652dda52b86f430738354b35

2023-11-09 20:33 UTC, EliteAsian123 commented on Assets/Script/Gameplay/HUD/LyricBar.cs
> +            lyricText = lyricText.Replace('§', ' ');
Yeah, if you can undo it that'll be great (since it doesn't have anything to do with the PR)

2023-11-09 20:56 UTC, raphaelgoulart commented on Assets/Script/Gameplay/HUD/LyricBar.cs
> +            lyricText = lyricText.Replace('§', ' ');
Fixed in https://github.com/YARC-Official/YARG/pull/588/commits/7661dd5b0b5213e7f63bd02c7da6e170750b28f0

2023-11-09 20:57 UTC, raphaelgoulart commented on Assets/Script/Venue/Lights/VenueAutogenerationPreset.cs
> +            AutogenerationSectionPreset sectionPreset = new AutogenerationSectionPreset();
Fixed in https://github.com/YARC-Official/YARG/pull/588/commits/7661dd5b0b5213e7f63bd02c7da6e170750b28f0

2023-11-12 20:43 UTC, EliteAsian123 commented
Merged in 3d62b5f55ae46cc283241ae1f1308dd4d5c79516 (PR did not close for some reason)

2023-11-12 20:43 UTC, closed without merging