Moved loading phrase from song select to difficulty screen
YARC-Official/YARG pull request #603
Opened 2023-11-23 20:17 UTC by TheFatBastid

It has been a long time coming but since things have settled down in terms of design, it seemed the right time to move the loading phrase from the cramped song select help bar location to the wide open difficulty screen

2023-11-23 20:29 UTC, RileyTheFox requested changes

2023-11-23 20:29 UTC, RileyTheFox commented on Assets/Script/Menu/DifficultySelect/DifficultySelectMenu.cs
> +            SetInfoText(RichTextUtils.StripRichTextTagsExclude(GlobalVariables.Instance.CurrentSong.LoadingPhrase, RichTextUtils.GOOD_TAGS));
Would prefer to use `StripRichTextTags(phrase, RichTextUtils.BAD_TAGS)` over the exclude function with the `GOOD_TAGS` constant. Just a little more clearer on what is being removed versus it being a double negative situation (stripping all except good tags vs stripping bad tags)

Not sure why it was written this way originally in the first place.

I think extracting the stripped text into a variable before passing it in would be a little easier to read as well (`string stripped = RichTextUtils.strip etc...` a line above). Also the `SetInfoText` function is redundant as setting the loading phrase text is only done once. Probably best to remove it.

2023-11-23 20:29 UTC, RileyTheFox commented on Assets/Script/Menu/DifficultySelect/DifficultySelectMenu.cs
> +        public void SetInfoText(string str)
I don't think the function is necessary as the loading phrase only ever gets set from one place in `OnEnable`. Would be fine to just set the `_loadingPhrase.text` field directly.

If for some reason the loading phrase were to be set from elsewhere in the future then a function would make sense.

2023-11-25 17:29 UTC, EliteAsian123 requested changes

2023-11-25 17:29 UTC, EliteAsian123 commented on Assets/Prefabs/Menu/DifficultySelect/DifficultySelectMenu.prefab
![image](https://github.com/YARC-Official/YARG/assets/29520859/9c17b5ed-def8-443d-b295-e88071208db3)

Anchor points are not set correctly so it does not align on different resolutions.

It's also recommended that you don't adjust these margins unless you absolutely have to:
![image](https://github.com/YARC-Official/YARG/assets/29520859/d16c38fd-430e-401f-b50e-cb81b98bf110)
Instead, choose one of the stretch options:
![image](https://github.com/YARC-Official/YARG/assets/29520859/cc86123d-5a15-4d2f-889d-75a752070dcf)

2023-11-30 20:59 UTC, closed without merging

2023-11-30 21:00 UTC, EliteAsian123 commented
Merged in 65171ab99e8533f62164293f10ff7fbd45b0818b (had to do it manually)