Added separate tracks for each harmony.
YARC-Official/YARG pull request #609
Opened 2023-12-02 00:56 UTC by JSanchez78657

Added separate tracks for each harmony.
Extended vocal track elements and moved practice mode elements to fit the larger vocal track. 
Removed desync of harmony lyrics since they can now be displayed with their correct timing.

2023-12-02 01:12 UTC, kaduwaengertner commented on Assets/Art/Textures/Gameplay/Track/VocalTrackHarmony.png
I'm going to redo this image so it matches the style, the extra lyric addition have a different contrast, I'll make the change and I'll send to Elite to add

2023-12-02 01:13 UTC, kaduwaengertner commented on Assets/Art/Textures/Gameplay/Track/VocalTrackNormal.png
Same for this, will edit the file to keep the style used, some of the effects got removed in the edit

2023-12-02 02:25 UTC, EliteAsian123 requested changes
Hi, thanks so much for your PR! I did a quick code review, so if you could fix those issues, that'll be great. I'll also do a review on the scene changes and that when I am able to. Thanks!

2023-12-02 02:25 UTC, EliteAsian123 commented on Assets/Script/Gameplay/Player/Vocals/VocalLyricContainer.cs
>              int i = harmIndex;
From your changes, `i` is now a useless variable and can be removed. There is one use case below which is incorrect.

2023-12-02 02:25 UTC, EliteAsian123 commented on Assets/Script/Gameplay/Player/Vocals/VocalLyricContainer.cs
>              if (!_pools[i].CanSpawnAmount(1))
Since `harmIndex` is being used to actually spawn in the lyrics, and `i` is not equal to `harmIndex` when on harmony 3, this could cause errors. Replacing `i` with `harmIndex` would fix this.

2023-12-02 04:55 UTC, JSanchez78657 commented on Assets/Script/Gameplay/Player/Vocals/VocalLyricContainer.cs
>              if (!_pools[i].CanSpawnAmount(1))
Replaced i with harmIndex

2023-12-03 03:29 UTC, kaduwaengertner commented
Sent the new files on Discord DM, make sure to adjust the tracks on Unity, noticed you cropped the top border on the edit you did, new ones have the right size on both border so might have to adjust a bit

2023-12-03 23:27 UTC, merged