Added support for some Santroller LEDs
YARC-Official/YARG pull request #626
Opened 2023-12-24 02:59 UTC by TheFatBastid

Santroller devices have LEDs on them. This will send commands to them for star power fill, star power activate, multiplier change, and solo start/end

2023-12-24 04:07 UTC, RileyTheFox requested changes
Overall the PR is good besides a couple things I'd change which I've outlined in some comments.

It's also worth thinking if this sort of thing could be abstracted into a dedicated player haptics class, which handles adding and removing devices as well as calling device specific code (for example santroller, or things like razer, logitech etc)

Let me know if you think that would be something we should do.

2023-12-24 04:07 UTC, RileyTheFox commented on Assets/Script/Gameplay/Player/BasePlayer.cs
> +            if (status)
This if statement can be removed and just pass the status variable in like `kit.SetStarPowerActive(status);`

2023-12-24 04:46 UTC, EliteAsian123 requested changes

2023-12-24 04:46 UTC, EliteAsian123 commented on Assets/Script/Gameplay/Player/BasePlayer.cs
> +            Player.Bindings.DeviceAdded += OnDeviceAdded;
In my opinion, subscribing to these events here is not the best. Instead, I think it would be better if the bindings contained a list of `ISantrollerHaptics` instead, which the player class can then access and call to. This will be especially useful in the future if we plan to add customization to this, so it can be configured in the binds menu or something of the like.

2023-12-26 09:07 UTC, TheNathannator commented on Assets/Script/Gameplay/Player/BasePlayer.cs
> +                SantrollerHaptics.ForEach(kit => kit.SetStarPowerActive(true));
I'd generally recommend not using the `ForEach` method on lists, it's just as easy to do a regular `foreach` loop and it avoids the delegate allocations that happen as part of calling `ForEach`. Here it's not super important though, as these aren't going to be called often enough for it to matter in the long run.

2023-12-26 09:10 UTC, TheNathannator commented on Assets/Script/Gameplay/Player/BasePlayer.cs
> +            Player.Bindings.DeviceAdded += OnDeviceAdded;
For now I think this approach works fine, it would probably be better to abstract things out once we know what we want to do for customization, other devices, etc. The only real customization options I can think of would be to enable/disable specific commands though, which could also be configured in the firmware itself instead of in-game.

Just want to make sure we avoid unnecessary complexity that we don't actually end up benefitting from.

2023-12-27 00:24 UTC, TheFatBastid commented on Assets/Script/Gameplay/Player/BasePlayer.cs
> +            Player.Bindings.DeviceAdded += OnDeviceAdded;
I didn't change this for now.

2023-12-27 16:46 UTC, EliteAsian123 approved these changes

2023-12-27 16:59 UTC, merged