Box Highlight Under Help Bar Buttons when Mouse Hovering
YARC-Official/YARG pull request #642
Opened 2024-01-01 01:40 UTC by Insomnautika

- Modified size and alignment of HelpBar_Buttons prefab plus added an image background that highlights when hovering with mouse and clicking.

[PREVIEW IMAGE]
![hoverhighlight2](https://github.com/YARC-Official/YARG/assets/154550825/a53e67a5-dbb4-429e-94ac-5d9c90b69841)

2024-01-01 05:45 UTC, kaduwaengertner commented
I would just remove the box coloring on the background, just keeping the text in yellow for the hover is enough, maybe we can also lower the opacity of the icons on default and change to 100% when hover also

2024-01-01 06:13 UTC, Insomnautika commented
The background box coloring is the only point of this pull request. Was trying to make it more clear the button was being hovered with the mouse besides just text color sense there is no change in the button icon when hovering. Makes it feel like you need to click on the text directly instead of it being clear the whole panel is a button. If you don't like this idea you can close the pull request.

2024-01-01 17:12 UTC, EliteAsian123 commented
I do agree that it does make it more clear of why you are supposed to click, and the fact that you can click it. Perhaps a different box coloring color could help?

2024-01-01 18:19 UTC, kaduwaengertner commented
Did some changes on figma, if we can change to something like this it would fit the style, subtle gradient instead of a full solid box
![image](https://github.com/YARC-Official/YARG/assets/87105274/cec270a4-1133-4dc5-892a-d32f7e973322)


Ideally the footer would be a gradient also, dont remember why we ended up using a solid footer but this was the original concept:
![image](https://github.com/YARC-Official/YARG/assets/87105274/3f6dcac7-60d8-47de-bec9-a06c0ed9f8d8)

2024-01-01 18:34 UTC, Insomnautika commented
I can make it look like that. Give me a bit to update it.

2024-01-01 18:54 UTC, EliteAsian123 commented
The transparency gradient on the help bar didn't work because Unity's transparency quality is terrible on UI (thanks Unity for always being a pain for UI stuff, lol). I didn't spend too long on it, but if you could find a way to make it work without tons of banding, that'll be great.

2024-01-05 18:12 UTC, EliteAsian123 requested changes
Good work overall! I just requested a few small code changes.

2024-01-05 18:12 UTC, EliteAsian123 commented on Assets/Script/Menu/Persistent/HelpBarButton.cs
> +        private Color32 ButtonBackgroundColor;
Private fields should be name `_likeThis`. This field should be named `_buttonBackgroundColor`.
Along with this, this field should be of type `Color` instead of `Color32` (`Color32`s can be implicitly converted into the simpler `Color`).

2024-01-05 18:12 UTC, EliteAsian123 commented on Assets/Script/Menu/Persistent/HelpBarButton.cs
> +            _buttonBackground.color = new Color32(255, 255, 255, 0);
`Color.clear` should be used in place of `new Color32(255, 255, 255, 0)` (unless it causes lerping issues)

2024-01-05 18:12 UTC, EliteAsian123 commented on Assets/Script/Menu/Persistent/HelpBarButton.cs
> +            _buttonBackground.color = new Color32(255, 255, 255, 0);
Same here

2024-01-05 18:12 UTC, EliteAsian123 commented on Assets/Art/Menu/Backgrounds/HelpBarHighlight.png
Try to fix this issue if you can
![image](https://github.com/YARC-Official/YARG/assets/29520859/b6aba1be-1263-458e-bc93-6c9d23a1d92a)

2024-01-05 18:26 UTC, Insomnautika commented
Alright, I can make those changes. I'll let you know when its ready.

2024-01-06 20:04 UTC, EliteAsian123 approved these changes

2024-01-06 20:04 UTC, merged