DMX support, "Advanced" tab, Stagekit toggle
YARC-Official/YARG pull request #670
Opened 2024-02-08 18:20 UTC by TheFatBastid

Added scan (dmx over ethernet) support. Added an advanced settings tab. Added ability to turn off the stage kit.
Haukcode.sACN is now MIT licensed.

2024-02-08 21:10 UTC, TheFatBastid commented
> Seems like sACN _does_ have a NuGet package _with_ a license. Can you confirm that this is the same package, and if so, attempt to use it via NuGetForUnity instead of importing the files?
> 
> https://www.nuget.org/packages/Haukcode.sACN

Same thing. He just added the license today when I e-mailed him. :) The difference being that I removed all the reading code, as YARG won't be receiving anything so about 10k lines, if that weight doesn't matter I'll try the package.

2024-02-08 21:35 UTC, EliteAsian123 requested changes
Thanks, this is pretty awesome! Just a few styling and one important thing and this should be good!

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/Script/Integration/Sacn/SacnController.cs
> +        private const float TIME_BETWEEN_CALLS = 1f / TARGET_FPS;
Small nitpick, but I would group this these consts and readonlys like this

```cs
// DMX spec says 44 updates per second is the max
private const float TARGET_FPS = 44f; 
private const float TIME_BETWEEN_CALLS = 1f / TARGET_FPS;

// Each universe supports up to 512 channels
private const int UNIVERSE_SIZE = 512;

private const string ACN_SOURCE_NAME = "YARG";

// A 128-bit (16 byte) UUID that translates to "KEEP PLAYING YARG!"
private static readonly Guid AcnSourceId = new Guid("{4B454550-504C-4159-494E-475941524721}");

// THEN the rest of the fields...
```

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/Script/Integration/Sacn/SacnController.cs
> +                    Debug.Log("(Sacn) Unknown color: " + color);
Should probably be a warning or error

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/Script/Integration/Sacn/SacnController.cs
> +        private static int[] _yellowChannels;
If static variables are used like this, it should probably be a `MonoSingleton` instead.

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitGameplay.cs
> +            if ( (StageKitLightingController.Instance.StageKits.Count == 0 || SettingsManager.Settings.StageKitEnabled.Value == false) && SettingsManager.Settings.DMXEnabled.Value == false)
`x == false` or `x == true` is redundant. Use `!x` or `x` respectively.

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/Script/Settings/Types/DMXChannelsSetting.cs
> +        public override bool ValueEquals(int[] value)
Separate these methods with empty lines

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/Script/Settings/Types/DMXChannelsSetting.cs
> +            Max = 255;
Are these actually used? Better yet, make all of the `int[]` into `byte[]` instead!

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/Settings/Localization/Settings Shared Data.asset
> +    m_Key: Header.Lighting General
Localization keys should not have spaces in them. Should be `Header.LightingGeneral` instead.

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/packages.config
> +  <package id="UniRx" version="5.4.1.0" />
Is this package actually used in this PR?

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +            public ToggleSetting DMXEnabled { get; } = new(false);
Empty line after the region and also align the `{ get; }`s together like above

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +                );
The `);` should be on the same line as `DmxCallback`

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +            public static event System.Action<int[]> OnDMXChannelsChanged;
This is a no, no. See my comment on the callback for more info.

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +                OnDMXChannelsChanged?.Invoke(value);
What *should* be happening instead if that the `SacnController` should be a `MonoSingleton` and this should call a method within there like `SacnController.Instance.UpdateDMXChannels()`

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/Script/Integration/Sacn/SacnController.cs
> +        private void HandleValueChanged(int[] value)
This argument can be removed

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/Script/Integration/Sacn/SacnController.cs
> +                localAddress: SACNCommon.GetFirstBindAddress().IPAddress);
I'm not really sure how SACN works, but it *really really* should not be initialized *unless* the user specifically enables the settings, especially since we're dealing with network stuff and sending packets.

The DMX setting should use a callback to call a method within this class, to then initialize/destroy it. To be honest, we really should be doing that for the Discord integration as well.

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/Script/Integration/Sacn/SacnController.cs
> +            InvokeRepeating(nameof(Sender), 0, TIME_BETWEEN_CALLS);
`InvokeRepeating` is unoptimized if I remember correctly, and it's annoying to deal with, you should probably just use a timer within the `Update` method

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitLightingController.cs
> +        public Action<StageKitLedColor, StageKitLed> OnLedSet;
Make this into an `event`.

2024-02-08 21:35 UTC, EliteAsian123 commented on Assets/Prefabs/Menu/Common/InputField.prefab
>    m_OnSubmit:
Haven't looked at this in Unity yet, so it's hard to tell; is this change intentional?

2024-02-08 21:36 UTC, EliteAsian123 commented
> Same thing. He just added the license today when I e-mailed him. :) The difference being that I removed all the reading code, as YARG won't be receiving anything so about 10k lines, if that weight doesn't matter I'll try the package.

Overall, I'd recommend packages when possible, so things aren't a pain to update.

2024-02-08 21:46 UTC, TheFatBastid commented
> > Same thing. He just added the license today when I e-mailed him. :) The difference being that I removed all the reading code, as YARG won't be receiving anything so about 10k lines, if that weight doesn't matter I'll try the package.
> 
> Overall, I'd recommend packages when possible, so things aren't a pain to update.

![image](https://github.com/YARC-Official/YARG/assets/22178315/3bd8e24c-fd88-488d-ba1e-5eb6f3e584bc)
:(

2024-02-08 21:49 UTC, EliteAsian123 commented
Damn okay, in which case we don't have much of a choice

2024-02-08 21:57 UTC, TheFatBastid commented on Assets/Prefabs/Menu/Common/InputField.prefab
>    m_OnSubmit:
Probably not. I don't even know what kind of change that is. Only thing I did with InputField is added 8  of them to the DMX prefab.

2024-02-08 22:21 UTC, TheFatBastid commented on Assets/Script/Integration/Sacn/SacnController.cs
> +            InvokeRepeating(nameof(Sender), 0, TIME_BETWEEN_CALLS);
I attempted a few different things for this, unitask, timers, etc and they all seemed to be more erratic than InvokeRepeating. The sacn converter that receives these messages (from YARG) had an incoming fluctuating fps  27 - 46, whereas the InvokeRepeating gave it a rock solid 44. I'll try other methods again.

2024-02-09 01:54 UTC, RileyTheFox commented
You could ask if the package's framework targets can be updated. It should have no issues being listed for .NET Standard 2.1 if it's set to target .NET 7.

https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1

2024-02-09 20:57 UTC, EliteAsian123 commented
Yeah if you could do that that'll be great; I'd rather not include a bunch of library files unless *absolutely necessary*.

2024-02-10 20:23 UTC, EliteAsian123 approved these changes

2024-02-10 20:24 UTC, merged