YARG-176 Add button to go to currently-playing song in music player
YARC-Official/YARG pull request #690
Opened 2024-02-17 09:30 UTC by vinaykapadia

https://yarg.youtrack.cloud/issue/YARG-176/Add-button-to-go-to-currently-playing-song-in-music-player

2024-02-18 06:20 UTC, EliteAsian123 requested changes
Hi, sorry for the late review! Just one small change and this should be good to merge.

2024-02-18 06:20 UTC, EliteAsian123 commented on Assets/Script/Helpers/Extensions/SongMetadataExtensions.cs
> +            GlobalVariables.Instance.CurrentSong = song;
Setting this value probably isn't the best idea as it could have unintended side effects (if I'm going to be honest, this whole system isn't great in the first place). Instead, it should be a value accessible in the `MusicPlayer` itself, or a method in the `MusicPlayer` that takes you to the song.

2024-02-18 17:33 UTC, vinaykapadia commented on Assets/Script/Helpers/Extensions/SongMetadataExtensions.cs
> +            GlobalVariables.Instance.CurrentSong = song;
Cool I'll take care of that on Monday.

2024-02-19 17:19 UTC, vinaykapadia commented on Assets/Script/Helpers/Extensions/SongMetadataExtensions.cs
> +            GlobalVariables.Instance.CurrentSong = song;
Ok, done!

2024-02-20 21:28 UTC, merged