Added DMX Cue Change channel
YARC-Official/YARG pull request #706
Opened 2024-02-29 06:25 UTC by TheFatBastid

Whenever the lighting cue changes, a DMX channel will be set to a value. Useful for external programs that make light shows from incoming triggers, such as Light Jamz.

This will be the last time the stagekit code will be used like this, next I'll redo how the cues are handled and uncouple that from the stagekit code directly so anything can listen to it better.

2024-03-01 17:26 UTC, TheFatBastid commented
Also, this adds the DMX info panel when going to the light settings and fixes a few small bugs with DMX.

2024-03-01 21:37 UTC, EliteAsian123 requested changes
Hi, sorry for the late review! Just a few things and this should be good. The `CueEnum` enum is not ideal (something like a dictionary or array would be better so everything doesn't have to be redefined), but you mentioned you'd like to redo it so it's fine for now.

2024-03-01 21:37 UTC, EliteAsian123 commented on Assets/Script/Integration/Sacn/SacnController.cs
> +                    break;
Use `switch (scene.buildIndex)` instead with the `(int) SceneIndex.Gameplay` for example. Don't use strings when you can avoid it!

2024-03-01 21:37 UTC, EliteAsian123 commented on Assets/Script/Integration/Sacn/SacnController.cs
> +                    break;
Same as above

2024-03-01 21:37 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitGameplay.cs
>          protected override void OnChartLoaded(SongChart chart)
New line between method and field

2024-03-01 21:37 UTC, EliteAsian123 commented on Assets/Script/Settings/Metadata/PreviewBuilders/DMXInformationPanelBuilder.cs
> +            if (go == null) return;
These lines can just be removed.
```cs
Object.Instantiate(Information, uiContainer);
return UniTask.CompletedTask;
```

2024-03-01 21:37 UTC, EliteAsian123 commented on Assets/Script/Settings/Metadata/PreviewBuilders/DMXInformationPanelBuilder.cs
> +        private static readonly GameObject Information = Addressables
`private` fields should be `_camelCase`

2024-03-01 21:37 UTC, EliteAsian123 commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +
The leading zeros here are not necessary, they are only in the arrays above for alignment purposes.

2024-03-01 21:37 UTC, EliteAsian123 commented on Assets/Script/Settings/Types/DMXInformationPanelSetting.cs
What is this file? Is it used? Same with all of the changes below this

2024-03-01 23:20 UTC, TheFatBastid commented on Assets/Script/Settings/Types/DMXInformationPanelSetting.cs
Thought I needed that for localization setting to show up. Not needed, will remove.

2024-03-03 21:24 UTC, EliteAsian123 commented
Did the `OnSceneLoaded` changes get forgotten, or did it not work out?

2024-03-03 21:38 UTC, TheFatBastid commented
Oops, I was lumping that in with "well, it works for now will redo with rework", the change has been made.

2024-03-06 23:40 UTC, merged