Improve UX for Go To menu.
YARC-Official/YARG pull request #707
Opened 2024-03-01 19:33 UTC by vinaykapadia

For Artist, Album, or Artist-Album, the Go To... list had way too many items. This makes it so that you only get letters in the Go To menu, just like how Song Name works now, and it goes to the first item in the list with that letter.

2024-03-01 21:55 UTC, EliteAsian123 commented
I think it may be better to make this a setting or something. @sonicfind thoughts?

2024-03-01 23:31 UTC, vinaykapadia commented
I personally think it works better without a setting, makes the UX more consistent, but I'm not opposed to it either way.

2024-03-13 02:59 UTC, sonicfind requested changes

2024-03-13 02:59 UTC, sonicfind commented on Assets/Script/Menu/MusicLibrary/PopupMenu.cs
> +
Unfortunately, you forgot the `else`. As it is, you'll get `just by first letter` followed by everything coming afterwards anyways.
Also, the grouping is currently case sensitive, so `A` would be in a separate group from `a`.

2024-03-20 21:36 UTC, sonicfind approved these changes

2024-03-20 21:37 UTC, merged