YARG-209 Show Bad Songs count on Scan
YARC-Official/YARG pull request #711
Opened 2024-03-08 21:35 UTC by vinaykapadia

If there is a bad songs file, it will read the first line and extract the number of errors. A button will be shown with the number of errors. Clicking on the button opens the file.

2024-03-08 21:37 UTC, vinaykapadia commented on Assets/Script/Menu/Settings/SongManager/SongManagerHeader.cs
> +            FileExplorerHelper.OpenFolder(PathHelper.BadSongsPath);
I used the OpenFolder method, since there is no OpenFile method. It works right on Windows, but I couldn't test the OSX implementation. Someone should probably do that...

2024-03-08 22:07 UTC, EliteAsian123 commented
Hi, thanks for the PR!

To me, this looks like more of a hack, which we'd like to avoid.

What should happen is the song scanner should return some value that indicates the error(s), and shows a popup after scanning. The popup dialog can have like an “Open badsongs.txt” button for more info or something like that.

FWIW I do think the "Open badsongs.txt" button in the settings menu is a good idea, but it should probably be made to open the actual file instead of opening the folder it's in.

2024-03-08 22:36 UTC, EliteAsian123 commented
> The button does open the file. The OpenFolder() method doesn't technically need to be a folder, it can take in a file as well. At least on Windows, it would need to be tested on Mac.

Ah okay, I see. According to the documentation, it should work!
![image](https://github.com/YARC-Official/YARG/assets/29520859/aedb7bb2-f555-40be-b058-2ddbcbeba483)

2024-03-10 16:02 UTC, EliteAsian123 requested changes
Forgot to do this on my comment above, whoops

2024-03-13 23:15 UTC, vinaykapadia commented
Ok it's no longer hack-y. Didn't realize there was already a place where the bad songs count was stored, I'm reading that from the ChaceHandler now.

2024-03-17 17:33 UTC, EliteAsian123 commented
Sorry for the late response! A few more things:
![image](https://github.com/YARC-Official/YARG/assets/29520859/73f1e2a1-b8ca-4815-9f61-c50012ecd865)
The “Errors Found” button should follow the same colour scheme as the delete button down there. Use that shade of red with white text,

Upon restarting the game, the button turns into this:
![image](https://github.com/YARC-Official/YARG/assets/29520859/b2023576-fae5-4721-9c24-4048b737cc0b)
The text doesn't fit the button too well. It should probably just state "Errors Found" without the number.

Also `badSongsButton` should be `_badSongsButton`.

I would still prefer a popup right after the scan, but this is fine for now.

Thanks so much, and sorry once again!

2024-03-18 21:11 UTC, vinaykapadia commented
> The “Errors Found” button should follow the same colour scheme as the delete button down there. Use that shade of red with white text,

Yeah I'm terribly with visual stuff. Your idea is much better. Will do.

> The text doesn't fit the button too well. It should probably just state "Errors Found" without the number.

Sounds good, will do.

> Also badSongsButton should be _badSongsButton.

Sounds good, will do.

> I would still prefer a popup right after the scan, but this is fine for now.

Yeah a popup would have been nicer, but this is a good v1. Would need a UI person to make a popup though, you really don't want me handling that (see my work with just this button for an example why lol.

2024-03-18 22:40 UTC, vinaykapadia commented
Ok, made the changes.

2024-03-20 22:01 UTC, merged