Lighting Controller
YARC-Official/YARG pull request #718
Opened 2024-03-14 21:23 UTC by TheFatBastid

This breaks the IRL lighting into 3 parts (Controller, Interpreter, Hardware) so that things can be expanded, extended, and added too much more easily for future support of more things.

Since a lot of the code is just hacked up and moved around from the old code, I'm sure there is still some things that are in the wrong place or redundant. 

I've decided to leave how the sACN pause works (off after 2.5 seconds) for now so the code can be reviewed in time for the upcoming deadline and I also don't have the hardware to test a change to it at the moment. I'll add it to my youtrack lighting list.

2024-03-14 23:28 UTC, sonicfind requested changes

2024-03-14 23:28 UTC, sonicfind commented on Assets/Script/Integration/LightingController.cs
> +            }
A few things: 
1. the first condition tested in each of these if statements can be removed. if  `count == 0`, `index` will always be `>= count`.
2. The last one is using the wrong check. `>=` instead of `<`.
3. You're going to need to utilize while loops instead of if statements. If the game ends up stalling for an extended period of time, the songtime may already span past multiple nodes in any of the queried lists. The problem is that Update, as it is now, can only handle one of each type with the if statement. Using a while loop allows it skip directly to whatever the latest effects should be.
4. This is more of a future thing, but vocals are a bit problematic at the moment. The issue is that the actual *end of phrases* shouldn't be defined by the end of the last note in a phrase. Doing so is causing conflicts to appear with notes that extend into the next phrase. It'd probably be better if you used the minimum value between the phrase End marker and the end of the last note in a phrase.

2024-03-14 23:28 UTC, sonicfind commented on Assets/Script/Integration/LightingController.cs
> +        private GameplayBehaviour _gameplayMonitor;
Note: recommend placing the monitor variable below the other statics.

2024-03-22 01:03 UTC, TheNathannator requested changes
Things are looking quite a bit better overall, but there's a lot of things I'm not the most satisfied with. There's still a good amount of mismanaged state and logic that could be cleaned up, among other things. Also, merge conflicts need to be resolved.

Not everything needs to be addressed right away, at the absolute least these are notes for future reference. Either way, I want to take my own pass at some of this code and refactor some more stuff.

2024-03-22 04:31 UTC, TheFatBastid commented on Assets/Script/Integration/Sacn/SacnHardware.cs
> +                InvokeRepeating(nameof(Sender), 0, TIME_BETWEEN_CALLS);
I used that because it seemed to be the most stable. Using that, then checking the sacn converter, it received a rock-solid 44fps. Before that I did try unitask as well as update with a timer but they seemed to fluctuate wildly from 24 to 50 fps. I don't know why.

2024-03-22 21:04 UTC, TheNathannator commented on Assets/Script/Integration/Sacn/SacnHardware.cs
> +                InvokeRepeating(nameof(Sender), 0, TIME_BETWEEN_CALLS);
I see, probably fine to leave it then. I could also suggest using a separate thread for sending data, but rolling our own timing system for that would probably be significantly more effort.

Just make sure it will work correctly with the timescale changes that happen when pausing the game, that's my primary concern here after looking at the documentation.

2024-03-23 05:38 UTC, TheFatBastid commented on Assets/Script/Integration/Sacn/SacnHardware.cs
> +                InvokeRepeating(nameof(Sender), 0, TIME_BETWEEN_CALLS);
Depends on how we want to handle things. A converter (that follows spec anyways...) will consider a source disconnected after 2.5 seconds of not receiving a packet, turning everything connected off. So if the game is paused all the dmx fixtures will turn off after 2.5 seconds. In a home environment I can see that being a good thing. However for some environments like a more arcade setup on stage or at a school tournament or something, I can see that killing the razzle dazzle of it. Either way, the fog and strobe should be turned off so we don't get the fire department called on anyone's house or cause a seizure or something.

2024-03-23 05:45 UTC, RileyTheFox commented on Assets/Script/Integration/Sacn/SacnHardware.cs
> +                InvokeRepeating(nameof(Sender), 0, TIME_BETWEEN_CALLS);
Instead of turning the effects off, maybe you could just keep them frozen in state depending on what the effect is? I don't know if you can freeze a strobe light to be on or off but you could just make some equipment just stay the effect they were when the game was paused but frozen (so doesn't change colour or patterns)

2024-03-23 06:00 UTC, TheFatBastid commented on Assets/Script/Integration/Sacn/SacnHardware.cs
> +                InvokeRepeating(nameof(Sender), 0, TIME_BETWEEN_CALLS);
Sure, if we just send the packet over and over while paused (and thus not updated) that would freeze the colored lighting. The strobe can't be frozen like that. However, correct me if I'm wrong but there is no InvokeRepeating that is not timescale dependent? Which leads back to the other methods of timing the packet not being consistent.

2024-03-26 20:13 UTC, EliteAsian123 requested changes

2024-03-26 20:13 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitInterpreter.cs
> +                        ChangeCues(new MenuLighting());
The problem with the approach of creating a new instance of a class every time the lighting event changes, is that there are new allocations, which should be avoided. Now, the performant ways to do this are a lot uglier in most regards, especially when (in this case) cues have lots of methods that can be called on them. There are multiple things you can do about this, however the absolute easiest in this case would be to pre-create all of the cues and store those instances in a list, then whenever they're needed, reset their state and change the cue to that instance.

If you're curious, a better way of doing this is present in the venue's `LightManager`, although, quite a bit simpler, but also has the downside of being quite a bit uglier.

2024-03-28 20:09 UTC, EliteAsian123 commented
Instead of doing all of the `FirstOrDefault` stuff, it'd probably be easier and more efficient to use a `Dictionary<LightingType, StageKitLightingCue>` and then replace (or partially replace anyway) the switch statement with an access.

2024-03-28 21:05 UTC, EliteAsian123 requested changes
Thanks! Few more minor styling things and this should be good (unless someone else has something to say).

2024-03-28 21:05 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitInterpreter.cs
> +                else if (value.Type == LightingType.Keyframe_Next || value.Type == LightingType.Keyframe_Previous ||
Use `value.Type is LightingType.Keyframe_Next or LightingType.Keyframe_Previous or ect...`

2024-03-28 21:05 UTC, EliteAsian123 commented on Assets/Script/Integration/StageKit/StageKitInterpreter.cs
> +            new Dictionary<LightingType, StageKitLightingCue>
Use `new()` instead of `new Dictionary<LightingType, StageKitLightingCue>`

2024-03-30 17:23 UTC, TheNathannator commented on Assets/Script/Playback/BeatEventHandler.cs
> +            foreach (var (action, state) in _addStates)
It prevents enumeration errors caused by handlers being added/removed by other handlers, collections can't be modified while they're being enumerated.

This is kind of the only solution to the issue with dictionaries, as they can't be looped over by index like lists can. We probably could switch things to a list and make the action a part of the state struct however, and do a duplicates check when adding.

2024-03-30 17:23 UTC, EliteAsian123 commented on Assets/Script/Playback/BeatEventHandler.cs
> +            foreach (var (action, state) in _addStates)
It's needed in order to allow subscribing/unsubscribing within the event handlers themselves, otherwise, you'd be adding new handlers while looping through said handlers below.

2024-03-30 17:24 UTC, EliteAsian123 commented on Assets/Script/Playback/BeatEventHandler.cs
> +            foreach (var (action, state) in _addStates)
Jinx

2024-04-03 20:16 UTC, merged