Status Bar Improvements
YARC-Official/YARG pull request #751
Opened 2024-04-26 05:33 UTC by vinaykapadia

Moves Status information to the right and Build information to the left. Adds Time and Battery info.

I set the battery thresholds at 10, 40, and 90% for now. They're set as constants so they're easy to tweak any time.

2024-04-26 05:36 UTC, vinaykapadia commented
Don't merge yet. Adding toggles for Time and Battery display.

2024-04-26 05:56 UTC, vinaykapadia commented
Ok, toggles added. Can be merged now.

2024-04-26 19:29 UTC, vinaykapadia commented
Added an option to show the memory stats, may be interesting to some people.

Also organized it so all status bar options are available in one place:
![image](https://github.com/YARC-Official/YARG/assets/17637030/f349658d-ddc6-424e-a3bc-ffee0a52b106)

The FPS Counter option is still available under Graphics settings as well.

2024-04-26 19:33 UTC, vinaykapadia commented
Here's how it looks with all options enabled:
![image](https://github.com/YARC-Official/YARG/assets/17637030/6fd64d7f-8821-4203-8121-eedc8c2f8880)

2024-04-26 19:43 UTC, vinaykapadia commented
Added the memory icon. Here is an updated screen shot (without battery showing):
![image](https://github.com/YARC-Official/YARG/assets/17637030/f05a2c89-6f7f-4811-ab02-a50145dc2247)

2024-04-26 22:58 UTC, EliteAsian123 requested changes
Very nice, love it! Just a few minor tweaks and this should be good to go:

The spacing between the left and the right content is not the same if the battery icon isn't shown:
![image](https://github.com/YARC-Official/YARG/assets/29520859/619fb0eb-5280-499c-a9e1-9cf241547150)

It may be worth combining all of these new sprites into a singular sprite sheet (see `Art/Menu/Common/Icons` for some examples). Not needed, but it would tidy things up a bit.

2024-04-26 22:58 UTC, EliteAsian123 commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +            public ToggleSetting ShowBattery { get; } = new(false);
Align the `{ get; }` with the other ones to make it look neater.

2024-04-27 04:03 UTC, vinaykapadia commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +            public ToggleSetting ShowBattery { get; } = new(false);
Cool will do both.

2024-05-01 22:18 UTC, vinaykapadia commented
@EliteAsian123 done.

2024-05-01 22:44 UTC, merged