Wider text field for playlist category header text
YARC-Official/YARG pull request #754
Opened 2024-04-29 22:08 UTC by rk-exxec

for your long playlist name needs, fixes #753
![image](https://github.com/YARC-Official/YARG/assets/40037381/d0c82668-7c5d-405c-9e2c-83ce5fe0c5c5)

- Added a new group in the SongView prefab with a second primary text 8as suggested by EliteAsian
- The swap happens depending on which background is chosen, seems a bit hack, 

Feedback is appreciated. Not quite familiar with the codebase layout yet.

2024-04-30 19:43 UTC, EliteAsian123 commented
Instead, perhaps the `ViewType` should have a virtual property called something like `UseWidePrimaryText`, which is checked for in  `Show`.

2024-05-01 09:37 UTC, rk-exxec commented
Right, thats a better idea.

2024-05-01 21:56 UTC, EliteAsian123 requested changes
One more thing and this should be good to go!

2024-05-01 21:56 UTC, EliteAsian123 commented on Assets/Script/Menu/MusicLibrary/SongView.cs
> +                _categoryText.text = viewType.GetPrimaryText(selected);
Instead of doing this, the `_categoryText` can just be added here and it should handle everything for you:
![image](https://github.com/YARC-Official/YARG/assets/29520859/8de75cd3-5fbe-4b34-821f-352265401026)

2024-05-02 18:43 UTC, rk-exxec commented
Done!

2024-05-03 20:20 UTC, merged