Re-implement holding down the orange fret for section navigation in MusicLibrary
YARC-Official/YARG pull request #756
Opened 2024-05-02 02:49 UTC by poliwhirlge

Hold orange + strum up and down to go to next/previous sections, seems like a capability that was in a previous version as discussed here: https://github.com/YARC-Official/YARG/issues/755

https://github.com/YARC-Official/YARG/assets/141366895/3a81e04a-73d9-4605-a4fb-eb02ac788916

2024-05-03 21:35 UTC, EliteAsian123 requested changes
Thanks for the PR! A few adjustments and this should be good to go. Sorry for the wait!

2024-05-03 21:35 UTC, EliteAsian123 commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +                Where(viewTypeEntry => viewTypeEntry.v is SortHeaderViewType || viewTypeEntry.v is CategoryViewType).
Can be simplified to `viewTypeEntry.v is SortHeaderViewType or CategoryViewType`

2024-05-03 21:35 UTC, EliteAsian123 commented on Assets/Script/Menu/Navigation/NavigationScheme.cs
> +            public void InvokeHolddOffHandler(NavigationContext context)
Typo

2024-05-03 21:35 UTC, EliteAsian123 commented on Assets/Script/Menu/Navigation/NavigationScheme.cs
> +            public Entry(MenuAction action, string displayName, Action<NavigationContext> handler, Action<NavigationContext> onHoldOffHandler = null)
Thoughts on, instead of doing this, add an extra field to `NavigationContext` that contains the hold state? This way, a new action is not needed in each entry, and it can consolidate the action in the `MusicLibrary`.

2024-05-03 21:35 UTC, EliteAsian123 commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +            if (ctx.IsRepeat)
Using the orange fret repeat is kind of hacky. It should be a separate timer with a separate threshold within this class instead, as now *all* orange frets on all menus repeat.

2024-05-04 00:35 UTC, poliwhirlge commented on Assets/Script/Menu/Navigation/NavigationScheme.cs
> +            public Entry(MenuAction action, string displayName, Action<NavigationContext> handler, Action<NavigationContext> onHoldOffHandler = null)
The second Action callback is more to get access to an "on button up" event, as the first Action is fired on "on button down". The way it's been working is as soon as you hit the orange fret, the handler Action fires and the more options menu immediately opens, and I wanted to move that to when the fret is released instead (otherwise the whole hold fret + strum up and down wouldn't be possible).

It's possible to add a field to NavigationContext that indicates whether it's a button on or button off event, but wouldn't that mean that we'd have to change all our other NavigationScheme.Entry objects to not do anything on the button off?

2024-05-04 00:46 UTC, poliwhirlge commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +            if (ctx.IsRepeat)
Yeah agree that it would be a good idea to just localize it to MusicLibrary, I just don't know if it's possible to know if the fret is being held down from MusicLibrary because I previously I believe the Navigator singleton only fires the event once unless we let the orange fret event repeat. I guess if we let the MusicLibrary listen directly to the InputManager we can have let it have its own timer within but that seems like breaking abstraction even more.

I'll keep thinking about ways to make this cleaner, thanks for the feedback.

2024-05-04 00:50 UTC, EliteAsian123 commented on Assets/Script/Menu/Navigation/NavigationScheme.cs
> +            public Entry(MenuAction action, string displayName, Action<NavigationContext> handler, Action<NavigationContext> onHoldOffHandler = null)
Fair

2024-05-04 00:52 UTC, EliteAsian123 commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +            if (ctx.IsRepeat)
I'm pretty sure that won't be needed. If you track when it gets first held down, you can update the orange button state within the update method with a check. I'm on mobile so apologies if I'm missing something.

2024-05-04 01:21 UTC, poliwhirlge commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +            if (ctx.IsRepeat)
Yeah makes sense, that would work, I'm not sure how to check if the orange button is held down though since at that point we don't have the GameInput object. Would it be Unity's Input.GetKey? Not seeing that used anywhere else in the code base though.

2024-05-04 01:35 UTC, EliteAsian123 commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +            if (ctx.IsRepeat)
You should be able to just do it off of the press and the new release actions you made.

In the press method, start a timer.

In the release method, if the timer has been active for X seconds, stop holding, otherwise open the more options menu.

2024-05-04 01:38 UTC, poliwhirlge commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +            if (ctx.IsRepeat)
Duh, yeah of course. Thanks!

2024-05-04 20:34 UTC, poliwhirlge commented
Made the changes (just re-used the HoldContext class), it also filters by player now so player A holding down the fret won't affect B's scrolling..

2024-05-05 14:19 UTC, EliteAsian123 requested changes

2024-05-05 14:19 UTC, EliteAsian123 commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +            foreach (var _heldInput in _heldInputs)
Only private fields should be prefixed with an underscore. Local variables should just be `heldInput`

2024-05-05 14:19 UTC, EliteAsian123 commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +            var holdContext = _heldInputs.Where(i => i.Context.IsSameAs(ctx));
It may be worth doing this instead:
```cs
var holdContext = _heldInputs.FirstOrDefault(i => i.Context.IsSameAs(ctx));
```
This way you don't have to worry about the possibility of having multiple hold contexts, and you avoid potential multiple enumerations.

In the case where there are multiple hold contexts for whatever reason, they should be dealt with by the `RemoveAll`.

2024-05-05 14:22 UTC, EliteAsian123 requested changes

2024-05-05 14:22 UTC, EliteAsian123 commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +                    (NavigationContext ctx) => {
The `NavigationContext` type is not needed here. Just do `(ctx) => {` or `ctx => {`.
Also, braces should be on the next line.

2024-05-05 14:22 UTC, EliteAsian123 commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +        }
This method should be placed near `OnButtonHit`, instead of at the top.

2024-05-05 14:22 UTC, EliteAsian123 commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +        private List<HoldContext> _heldInputs = new();
This field should be placed with the other fields.

2024-05-05 14:53 UTC, poliwhirlge commented
Cool, think I got everything, thanks for the reviews!

2024-05-05 22:28 UTC, EliteAsian123 commented
Thanks!

2024-05-05 22:28 UTC, merged