update 4L Cymbal binding strings to account for Lefty Flip
YARC-Official/YARG pull request #757
Opened 2024-05-02 12:09 UTC by W-Livi

Renumbered four-lane cymbals to match their lanes, expanded Green Cymbal string to encompass its role as Red Cymbal

2024-05-03 21:42 UTC, EliteAsian123 commented
![image](https://github.com/YARC-Official/YARG/assets/29520859/18bfd5cb-5f34-4465-a759-7cb0f0d32de7)
I think having this displayed is a little bit clunky, so perhaps it should swap the displayed text when left flip is turned on

2024-05-09 05:02 UTC, W-Livi commented
Thank you for the constructive criticism; I agree that just mashing the two together was kinda messy. This new commit adopts your suggested approach.

The new result is still a _little_ awkward, in that a lefty player sees
- Yellow Cymbal (Second)
- Blue Cymbal (Third)
- Red Cymbal (First)

Perhaps I should look into some means of specifying an alternate sequence for lefty binds, to go alongside the alternate labels.

2024-05-19 21:14 UTC, EliteAsian123 requested changes

2024-05-19 21:14 UTC, EliteAsian123 commented on Assets/Script/Input/Bindings/ControlBinding.cs
> +        public ControlBinding(string name, string namelefty, int action)
The argument should probably be named `nameLefty` to adhere to naming conventions.

2024-05-19 21:14 UTC, EliteAsian123 commented on Assets/Script/Menu/ProfileInfo/EditBinds/BindGroups/BindHeader.cs
> +            if (player.Profile.LeftyFlip) {
Make sure to follow the proper brace styling (new line before brace).

2024-05-19 21:40 UTC, W-Livi commented on Assets/Script/Menu/ProfileInfo/EditBinds/BindGroups/BindHeader.cs
> +            if (player.Profile.LeftyFlip) {
Thank you for pointing this out; I'm not sure how I missed the style y'all use, especially since it was already on clear display - `else` included - in this same method.

2024-05-19 22:00 UTC, merged