Changed callbacks to lamdas
YARC-Official/YARG pull request #789
Opened 2024-05-30 20:38 UTC by TheFatBastid

Removed unneeded  IsInitialized checks

2024-05-30 20:51 UTC, RileyTheFox commented on Assets/Script/Integration/Sacn/SacnInterpreter.cs
> +            YargLogger.LogInfo("In OLE IN SI: ON Lighting event: " + newType.Type);
This should really be a Debug or even Trace level log

2024-06-01 22:25 UTC, EliteAsian123 requested changes
Some styling changes and this should be good!

2024-06-01 22:25 UTC, EliteAsian123 commented on Assets/Script/Integration/MasterLightingController.cs
> +        public static void Initializer(Scene scene)
Make sure to add spacing between methods

2024-06-01 22:25 UTC, EliteAsian123 commented on Assets/Script/Integration/MasterLightingController.cs
> +        private static void OnApplicationQuit()
Here as well

2024-06-01 22:25 UTC, EliteAsian123 commented on Assets/Script/Integration/RB3E/RB3EHardware.cs
> +        public IPAddress _ipAddress = IPAddress.Parse("255.255.255.255"); // "this" network's broadcast address
Make sure to update the naming style of the field when you change it to public (should be `IPAddress`)

2024-06-01 22:25 UTC, EliteAsian123 commented on Assets/Script/Integration/Sacn/SacnInterpreter.cs
> +        public int _keysChannel;
Same here

2024-06-01 22:25 UTC, EliteAsian123 commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +                new[] { 01, 09, 17, 25, 33, 41, 49, 57 }, v => { SacnInterpreter.Instance._dimmerChannels = v;});
For one-line lambdas, braces are not required. This can be changed to `v => SacnInterpreter.Instance._dimmerChannels = v`.

2024-06-04 22:20 UTC, EliteAsian123 requested changes

2024-06-04 22:20 UTC, EliteAsian123 commented on Assets/Script/Integration/Sacn/SacnInterpreter.cs
> +        public int keysChannel;
Public fields should be in `PascalCase`, regardless of there serializability (as Rider may suggest). We have chosen to ignore serializability for YARG field naming.

2024-06-05 19:24 UTC, merged