Drum velocity
YARC-Official/YARG pull request #794
Opened 2024-06-07 20:12 UTC by Purplo-cf

Unity prefab setup for ghost/accent notes for both pads and cymbals in the Rectangular theme - Four lane and Five lane compatible. These are purely placeholders and need a LOT of design love. I got the models from Kadu but I'm pretty sure I assigned the materials to the wrong meshes.

Changed all drum IndividualButtonBindings to a new velocity-sensitive DrumPadButtonBinding subclass

2024-06-07 20:20 UTC, Purplo-cf commented on Assets/Script/Input/Bindings/ControlBinding.cs
This was the easiest way that I could find to extend FireInputEvent on DrumPadButtonInput to accept a float value. I made this a virtual method in ControlInput and I'm overriding it in DrumPadButtonInput. I saw Nathan mention something recently about virtual methods aren't great for performance, so let me know if there's a better way to handle this.

2024-06-07 20:24 UTC, Purplo-cf commented on Assets/Script/Input/Bindings/DrumPadButtonBinding.cs
IndividualButtonBinding sends out IsPressed as a bool value, so I'm trying to capture that FireInputEvent call here and send the highest axis value of all mapped SingleBindings. This should adjust automatically if a player adjusts their press threshold in their profile right?

2024-06-08 01:44 UTC, EliteAsian123 requested changes
Hi, thanks for the PR!

It appears the YARG.Core submodule pointer is broken, so I haven't tested this in-game, however, I've still pointed out some things I noticed below.

I'll also request a review from Nathan for the input stuff as he knows more than I do when it comes to that.

Thanks again!

2024-06-08 01:44 UTC, EliteAsian123 commented on Assets/Art/Fonts/Barlow/Barlow-Italic.asset
Was this file meant to be changed? If not, it should be reverted. Sometimes Unity randomly modifies files.

2024-06-08 01:44 UTC, EliteAsian123 commented on Assets/Art/Meshes/Gameplay/Notes/Rectangular/Cymbal_Accent.fbx
The model file names should match those of the already existing ones. For example, `AccentCymbalNote` or `CymbalAccentNote` may be a better name for this. Same with the other models added!

2024-06-08 01:44 UTC, EliteAsian123 commented on Assets/Scenes/PersistentScene.unity
I'm also assuming this was an unintentional change

2024-06-08 01:44 UTC, EliteAsian123 commented on Assets/Script/Gameplay/Visuals/TrackElements/Drums/FiveLaneDrumsNoteElement.cs
> +                        _                      => false
This can just be converted into a simpler expression of
```
bool isCymbal = (FiveLaneDrumPad) NoteRef.Pad is 
    FiveLaneDrumPad.Yellow or FiveLandDrumPad.Orange;
```

2024-06-08 01:44 UTC, EliteAsian123 commented on Assets/Script/Input/Bindings/BindingCollection.Templates.cs
>              // TODO: Velocity support
This TODO can be removed

2024-06-09 02:53 UTC, Purplo-cf commented
> It appears the YARG.Core submodule pointer is broken, so I haven't tested this in-game, however, I've still pointed out some things I noticed below.

Sorry about that! I'm not totally sure what happened the first time, but git let me update the pointer for today's changes so I'm hoping that fixed it 🤞

Thanks for the quick replies on all of this!

2024-06-09 20:00 UTC, TheNathannator approved these changes
Seems good from an initial look-over! I'll have to do some playing around with things when I get the chance, but this should work.

2024-06-14 19:35 UTC, Purplo-cf commented
Rad - Thank you 🤘!

I think I updated the pointer correctly - let me know if I need to make any changes!

2024-06-14 19:41 UTC, merged