Drum Hit SFX
YARC-Official/YARG pull request #802
Opened 2024-06-15 19:35 UTC by raphaelgoulart

Should be good to be reviewed, but it's not final because I'm waiting on real drum samples by Jarod Fedele.

TODO:
- Add localization string to the DrumSfxVolume setting because I literally forgot;
- Replace placeholder samples with real ones;
- Move drum sfx loading/disposal to song start/end respectively IF there are any drum players (I'll definitely need help with this one; as of right now it just loads on game start like regular SFX, which is not terrible but that's some RAM being wasted)

2024-06-16 22:50 UTC, EliteAsian123 requested changes
Overall pretty good; the sample stuff will likely need improvement but that's not really my expertise so I won't comment on that.

Also, when you get the real samples, if you could provide them as `.ogg` (since they're smaller, probably) that'd probably slightly speed the loading up along with decrease the game's file size.

2024-06-16 22:50 UTC, EliteAsian123 commented on Assets/Art/Fonts/Barlow/Barlow-Italic.asset
This probably was an unintentional change

2024-06-16 22:52 UTC, raphaelgoulart commented on Assets/Art/Fonts/Barlow/Barlow-Italic.asset
Whoops, didn't notice as it was between other actual changes (Unity L) - will revert now

2024-06-16 22:54 UTC, raphaelgoulart commented
Also yeah I can provide final samples as `.ogg`, but does the game support `.opus` for SFX? They're slightly more efficient

If not, 112kbps oggs are probably more than good enough!

2024-06-16 22:55 UTC, EliteAsian123 commented
Not sure honestly, but if they do that'd probably be even better. Thanks!

2024-06-16 23:06 UTC, raphaelgoulart commented
Can confirm .opus works, sample sizes went from 13mb to about 500kb! Yeah I'll def do that once the real samples arrive

2024-06-19 18:26 UTC, sonicfind requested changes
On the audio side: pretty simple yea, just a few minor adjustments,

2024-06-19 18:26 UTC, sonicfind commented on Assets/Script/Audio/Bass/BassDrumSampleChannel.cs
> +            volume *= GlobalAudioHandler.GetVolumeSetting(SongStem.DrumSfx);
To go with the Core PR review, the volume will already be pre-multiplied, so you won't need to do that here.

2024-06-19 18:26 UTC, sonicfind commented on Assets/Script/Audio/Bass/BassAudioManager.cs
> +        public void LoadDrumSfx()
`private`

2024-07-12 14:39 UTC, RileyTheFox commented on Assets/Script/Audio/Bass/BassAudioManager.cs
> +                            YargLogger.LogFormatInfo("Loaded {0}", sfxFile);
Given how many samples there are to load, I think it may be better to only log if a sample failed to load rather than every time one is loaded. Just to prevent useless log spam

2024-07-12 15:04 UTC, raphaelgoulart commented on Assets/Script/Audio/Bass/BassAudioManager.cs
> +                            YargLogger.LogFormatInfo("Loaded {0}", sfxFile);
Removed log, since an error is printed if it fails to load in the bass sample part of the code

2024-07-13 20:18 UTC, EliteAsian123 requested changes
Overall awesome, just a few style changes.

Are these the final samples now? I've seen the new ones in the Discord but the PR still says you're waiting for them. Just to make sure, we do have full legal permission to use the new samples, correct?

2024-07-13 20:18 UTC, EliteAsian123 commented on Assets/Script/Audio/Bass/BassDrumSampleChannel.cs
> +                YargLogger.LogFormatError("Failed to load {sample} {path}: {0}!", Bass.LastError);
Wait does `{sample} {path}` actually work? If so I did not know that lol

2024-07-13 20:18 UTC, EliteAsian123 commented on Assets/Script/Gameplay/Player/DrumsPlayer.cs
> +        private float DrumSoundEffectAccentThreshold;
Private variables should be named `_likeThis` (camel case with underscore)

2024-07-13 20:27 UTC, raphaelgoulart commented
> Overall awesome, just a few style changes.
> 
> Are these the final samples now? I've seen the new ones in the Discord but the PR still says you're waiting for them. Just to make sure, we do have full legal permission to use the new samples, correct?

Yes, I just forgot to update the text
And also yes, Jarod Fedele himself recorded those specifically **for** the game. Contact him if you need any confirmation

2024-07-13 20:33 UTC, raphaelgoulart commented on Assets/Script/Audio/Bass/BassDrumSampleChannel.cs
> +                YargLogger.LogFormatError("Failed to load {sample} {path}: {0}!", Bass.LastError);
I haven't had any situations where samples failed to load, but this is borrowed from BassSampleChannel.cs (presumably sonicfind's code) so it should work

2024-07-13 20:34 UTC, raphaelgoulart commented on Assets/Script/Gameplay/Player/DrumsPlayer.cs
> +        private float DrumSoundEffectAccentThreshold;
Fixed

2024-07-14 02:25 UTC, EliteAsian123 approved these changes

2024-07-19 16:37 UTC, sonicfind commented on Assets/Script/Audio/Bass/BassDrumSampleChannel.cs
> +                YargLogger.LogFormatError("Failed to load {sample} {path}: {0}!", Bass.LastError);
pfft it doesn't there either lol, it just *never happened* so it never got noticed

2024-07-19 20:59 UTC, raphaelgoulart commented on Assets/Script/Audio/Bass/BassDrumSampleChannel.cs
> +                YargLogger.LogFormatError("Failed to load {sample} {path}: {0}!", Bass.LastError);
fixed then lol

2024-07-20 02:46 UTC, sonicfind requested changes

2024-07-20 02:46 UTC, sonicfind commented on Assets/Script/Gameplay/Player/DrumsPlayer.cs
> +            if (IsDrumFreestyle())
This check isn't needed as that's already accounted for before calling the function on line 132

2024-07-20 02:46 UTC, sonicfind commented on Assets/Script/Gameplay/Player/DrumsPlayer.cs
> +                else if (velocity > EngineParams.VelocityThreshold)
Probably wanna add a comment here stating `VelocityThreshold` maps to the "ghosting" line.

2024-07-20 02:46 UTC, sonicfind commented on Assets/Script/Gameplay/Player/DrumsPlayer.cs
> +                    sampleVolume = velocity / _drumSoundEffectAccentThreshold;
Plus one here (and in the next branch) stating the division is normalizing the volume using `_drumSoundEffectAccentThreshold` as a pseudo `"1"`

2024-07-20 02:46 UTC, sonicfind commented on Assets/Script/Gameplay/Player/DrumsPlayer.cs
> +            return Engine.State.NoteIndex == 0 || Engine.State.NoteIndex >= Notes.Count; // TODO: add drum fill / BRE conditions
Assuming `wasNoteHit` being `true` in the `engine.OnPadHit` lambda also means that it already incremented `Engine.State.NoteIndex`, this may cause a drum sfx to play every time the last note of a chart is played.

You can only truly solve this by making drum sfx activate/deactivate based purely on the presence of notes in a certain timeframe instead of by note index. Something along the lines of: "If the distance between these notes is greater than [value] & current time is outside of either note's hit window, allow sfx" + plus the BRE fill and start/end cases.

2024-07-20 10:39 UTC, raphaelgoulart commented on Assets/Script/Gameplay/Player/DrumsPlayer.cs
> +            return Engine.State.NoteIndex == 0 || Engine.State.NoteIndex >= Notes.Count; // TODO: add drum fill / BRE conditions
This isn't needed because `if (wasNoteHit) return;` (line 100) ensures the remaning of the `engine.OnPadHit` code won't be ran (and as such, `PlayDrumSoundEffect(action, velocity);` won't be triggered)

And in my tests this is exactly what happens - not once I had the drum sfx being triggered on the last note of a song, only afterwards

2024-07-20 15:52 UTC, sonicfind approved these changes

2024-07-20 16:31 UTC, merged