Feature/whammy
YARC-Official/YARG pull request #812
Opened 2024-07-01 06:20 UTC by jbienz

Added pitch bending whammy support back in. I submitted another PR for YARG.Core to support these changes and I will open a discussion in this feature request:

https://github.com/YARC-Official/YARG/issues/786

Here are the changes I implemented to restore this feature:

1. Added WhammyPitch (double) to StemSettings

2. Added OnWhammyPitchChange to StemSettings

3. In StemChannel subscribed to OnWhammyPitchChange at the same location volume change is called

4. In GlobalAudioHandler added Get/SetWhammyPitchSetting 

5. In StemState added SetWhammyPitch.

6. In SettingsManager.Settings uncommented UseWhammyFx setting and UseWhammyFxChange.

7. In SettingsManager.Settings uncommented WhammyPitchShiftAmount setting and WhammyPitchShiftAmountChange.

8. In GameManager.Audio added ChangeStemWhammyPitch

9. In FiveFretPlayer added SetStemWhammyPitch

10. In FiveFretPlayer called SetStemWhammyPitch in override for OnInputQueued when WhammyFactor is updated.
In GlobalAudioHandler changed WHAMMY_FFT_DEFAULT to 512 to try and reduce latency between guitar track and other tracks when pitch change is enabled.

2024-07-02 05:47 UTC, jbienz commented
I have updated this PR to move the Whammy settings under Experimental Features. This means that the following PR would need to be merged before this one can be merged:

https://github.com/YARC-Official/YARG/pull/815

2024-07-03 03:17 UTC, jbienz commented
Updated to incorporate changes made in https://github.com/YARC-Official/YARG/pull/815.

2024-07-09 04:28 UTC, sonicfind requested changes

2024-07-09 04:28 UTC, sonicfind commented on Assets/Script/Gameplay/GameManager.Audio.cs
> +
With my recommendation of disallowing multiple players to share a stem for whammying purposes, this function and the variable wouldn't need to be added.

2024-07-22 21:03 UTC, sonicfind commented
Heads up, I've mentioned this to a few others, but don't use merge when you're handling a PR. Always **rebase**. If you merge, it becomes hard to follow some of the flow of changes made through each commit as it fills the branch with nondescript updates. Yours isn't as bad as others, but you do still have five merge commits in this PR.

2024-07-23 23:02 UTC, jbienz commented on Assets/Script/Gameplay/GameManager.Audio.cs
> +        }
Yes, it's certainly possible for more than one player to be Guitar or Bass. I would still like to allow it, even if there are multiple guitarists. This happens often at our parties. Perhaps that's another option?

- Disabled
- Single Instrument
- Shared Instrument

Or something like that?

2024-07-23 23:04 UTC, jbienz commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +            public ToggleSetting UseWhammyFx { get; } = new(false, UseWhammyFxChange);
I thought about this, but what would be the case for On (not Multitrack)? Wouldn't you be pitch bending the entire song, lyrics and all? Is that desired?

Or were you suggesting the same thing I was just with different naming? That we give an option to enable when more than one user shares the instrument?

2024-07-23 23:06 UTC, jbienz commented on Assets/StreamingAssets/lang/en-US.json
> +                "Description": "Enables pitch bending in response to the whammy bar on multi-track charts.\nWARNING: This setting is known to cause audio desync issues on some machines."
Maybe I'm missing the definition of multi-track? I thought multi-track meant stems, where guitar could be pitch bent separate from the rest of the track. If that's correct, I'm back to being confused about when we would want to support single track because I would think that would cause the entire song to pitch bend. Sorry if I'm missing something.

2024-07-23 23:07 UTC, jbienz commented on Assets/Script/Audio/Bass/BassStemChannel.cs
>              percent = Mathf.Clamp(percent, 0f, 1f);
Okay. So I think you're saying don't clamp here just pass it on right?

2024-07-24 14:00 UTC, sonicfind commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +            public ToggleSetting UseWhammyFx { get; } = new(false, UseWhammyFxChange);
`On` behaves like `Multitrack` if the player has its own stem. It only differs in that if they gets set to the default/background stem, you'd still be able to whammy it.

2024-07-24 14:01 UTC, sonicfind commented on Assets/Script/Audio/Bass/BassStemChannel.cs
>              percent = Mathf.Clamp(percent, 0f, 1f);
correct

2024-07-24 16:53 UTC, sonicfind commented on Assets/Script/Gameplay/GameManager.Audio.cs
> +        }
But again, you basically set up situations where players have their whammies being completely ignored purely based on someone else having priority (against their choice). The only way to have any sort of fairness would be to add some weighting or averaging, but these functions aren't built for that. You'd need to add functionality that sets the collective amounts of whammy percentage to zero on every frame. This also relies on the inputAction being sent every frame as well. If it is, then cool, but if not, then even that fails as stationary values won't be read on subsequent frames.

2024-08-09 18:20 UTC, sonicfind commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +            public ToggleSetting UseWhammyFx { get; } = new(false, UseWhammyFxChange);
I guess `All` would be a better alternative.

2024-08-09 19:58 UTC, sonicfind commented on Assets/StreamingAssets/lang/en-US.json
> +                "Description": "Enables pitch bending in response to the whammy bar on multi-track charts.\nWARNING: This setting is known to cause audio desync issues on some machines."
As mentioned, the third option would behave like multitrack *except* that the background stem could have whammy effects applied as well if an instrument ends up mapped to it.

2024-08-10 22:48 UTC, jbienz commented
Replacing this PR with #846

2024-08-10 22:48 UTC, closed without merging