Feature/experimental
YARC-Official/YARG pull request #815
Opened 2024-07-02 05:45 UTC by jbienz

Added new hidden menu for Experimental Features. This menu is tucked away under developer settings. When enabled, the user is presented with large red text in the Sidebar noting that features shown on this page are unsupported.

There are no experimental settings in this pull request, but my Whammy FX PR has been updated to show its settings under Experimental.

https://github.com/YARC-Official/YARG/pull/812

![ZKtAzzyXNn](https://github.com/YARC-Official/YARG/assets/2062886/b8a0448f-1989-4e09-86f8-305a8a23235f)

![O2HXaYhpXz](https://github.com/YARC-Official/YARG/assets/2062886/179eb1e2-af8d-4280-a1df-e188fa19ac13)

![stfZRlzY33](https://github.com/YARC-Official/YARG/assets/2062886/514ddcf1-80e5-4a90-ad01-8aba2191d5b8)

2024-07-02 12:00 UTC, RileyTheFox commented
Before I test this I just want to mention that in future all PRs should target the `dev` branch. `master` is for stable releases and is merged to from `dev`, which is our 2 per day nightly release branch. I've changed this for you but in future try to remember!

2024-07-02 16:51 UTC, jbienz commented
> Before I test this I just want to mention that in future all PRs should target the `dev` branch. `master` is for stable releases and is merged to from `dev`, which is our 2 per day nightly release branch. I've changed this for you but in future try to remember!

I'm sorry Riley. I was aware of that requirement and I thought I had been careful to follow it. I will be even more vigilant next time.

2024-07-02 18:27 UTC, EliteAsian123 requested changes
Hi, thanks for the PR! I've submitted some minor feedback below.

The tab icon doesn't really artistically fit with the rest, however, I'll replace it later so don't worry about it.

2024-07-02 18:27 UTC, EliteAsian123 commented on Assets/Script/Settings/Metadata/PreviewBuilders/ExperimentalPreviewBuilder.cs
> +            // No other configuration required
These statements aren't needed as there is nothing after them (only the instantiation is required).

2024-07-02 18:27 UTC, EliteAsian123 commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +
Having a toggle to show/hide the settings might be a little overkill, as people may not know that the experimental settings exist. Showing the tab at all times with the warning should be good enough.

2024-07-02 18:27 UTC, EliteAsian123 commented on Assets/Settings/Localization/Settings_en-US.asset
> +      These settings are experimental and are not supported.'
Maybe change this to "these settings are experimental and could cause major problems if enabled."

2024-07-02 18:30 UTC, jbienz commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +
I'm fine with showing it all the time. @RileyTheFox seemed a little concerned about the support issues that could be raised, though that's why I added the big red text. @RileyTheFox what are your thoughts? Would you prefer it to stay hidden under a developer option or are you OK with it being visible all the time?

2024-07-02 20:52 UTC, RileyTheFox commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +
I think settings being explicitly under an experimental tab should be enough to tell users that the features there are incomplete/prone to issues. I raised concern in regards to #812 as it would have originally been added to the audio settings, and I didn't want people thinking its a complete feature then bombarding us with help/bug reports when we know full well it has problems. 

For the experimental tab, we could maybe show a popup for the first time the user clicks on it explaining that everything inside it is work in progress/subject to change/will contain bugs. Thoughts on that? @EliteAsian123

2024-07-02 20:54 UTC, EliteAsian123 commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +
Yeah, it can be one of those dialog boxes with the "don't show again" checkbox.

2024-07-03 02:44 UTC, jbienz commented on Assets/Script/Settings/Metadata/PreviewBuilders/ExperimentalPreviewBuilder.cs
> +            // No other configuration required
I removed these lines of code and instead show the dialog which can be opted out.

2024-07-03 02:45 UTC, jbienz commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +
I made the menu visible by default but now show a dialog when the menu is first displayed. The dialog can be opted out similarly to the piracy dialog.

2024-07-03 02:45 UTC, jbienz commented on Assets/Settings/Localization/Settings_en-US.asset
> +      These settings are experimental and are not supported.'
I updated the text as suggested.

2024-07-03 02:45 UTC, jbienz commented
Updated TabIcon to use Lucide icon. Made Experimental tab always visible under All Settings. Added dialog shown when entering Experimental Features. This dialog is shown once per launch and can also be marked to not show again. Added new localized strings for the dialog and title. Removed old localized  strings for the previous setting to show and hide the Experimental section.

2024-07-03 19:44 UTC, EliteAsian123 commented
This looks good to me for merging, however, there were just some localization changes pushed that will require some changes in this PR. After that, I'll merge! Thanks.

2024-07-03 20:17 UTC, jbienz commented
The localization assets appear to have been removed and I don't see any documentation on how strings should now be localized in your new system. @EliteAsian123 can you please make the required changes, or please tell me the necessary steps to use your new localization system?

2024-07-04 02:26 UTC, merged