Countdown rework
YARC-Official/YARG pull request #825
Opened 2024-07-14 21:56 UTC by Purplo-cf

Top-level changes for countdown rework. Unity elements that are no longer necessary have been removed

2024-07-19 16:50 UTC, RileyTheFox commented on Assets/Script/Gameplay/HUD/CountdownDisplay.cs
> +        private bool _displayState;
I think this boolean could use a slightly more clear name personally. I had to look at where the value is set to understand what it was. Something like `_displayActive` would be better I think

2024-07-19 16:51 UTC, RileyTheFox commented on Assets/Script/Gameplay/HUD/CountdownDisplay.cs
>          private void ToggleDisplay(bool newState)
If going through with the state variable rename, this should also be `bool active` or something.

2024-07-19 16:53 UTC, RileyTheFox reviewed
Besides the small comments, looks good. I think for some extra customisation we could have a setting to change the display into a seconds countdown instead of measures? I know some people prefer a countdown in seconds, and Clone Hero has this option too, so it would be nice to have here.

Display setting should default to measures and have the option to change it to seconds.

2024-07-19 16:53 UTC, RileyTheFox commented
@EliteAsian123 @kaduwaengertner what do you think regarding the suggestion above?

2024-07-19 16:57 UTC, EliteAsian123 commented
I'm always for customization 👍

2024-07-19 18:24 UTC, kaduwaengertner commented
I like the idea

2024-07-20 04:02 UTC, Purplo-cf commented
The new setting and the requested fixes are in. This will need the latest `countdown-rework-core` changes to run

2024-07-29 03:53 UTC, EliteAsian123 commented
Ah shoot wait, I'm dumb. I made some changes to the countdown prefab on `engine-refactor` because I didn't see that this PR changes those. 

Essentially I just made sure to change all `Transform`s to `RectTransform`s on the prefab and removed the scaling on the transforms as that's bad practice. I'll revert the changes on the main branch to prevent potentially broken prefabs from merging.

2024-07-29 04:48 UTC, Purplo-cf commented
No worries! I did a rebase this morning to double check that everything still looked okay. Okay had to make a few small adjustments

2024-08-02 14:43 UTC, RileyTheFox requested changes
Some issues I've noticed:

Something has corrupted and the lyric bar is just a white box now. I got a warning in Unity when checking out the branch "Broken text PPtr in file". It was referencing fileID `6635242913724598267` which is found as the m_Father in some places in CountdownDisplay.prefab

![image](https://github.com/user-attachments/assets/a4618f30-9eb1-44b3-87f7-53ae2f9b8e86)

Also in practice mode, if you select a section that occurs after a countdown earlier in the song, it will show the last part of the countdown. However this is a general engine issue with practice mode that has only come up now (queued updates being generated from time 0 up to the practice section time) so I will handle this at a later point.

2024-08-03 14:28 UTC, RileyTheFox approved these changes

2024-08-03 14:28 UTC, merged