More missing localization
YARC-Official/YARG pull request #828
Opened 2024-07-20 22:55 UTC by Purplo-cf

Added missing localization keys for menu headers and actions in the Music Library popup menu and on the Difficulty Select screen.

2024-07-23 20:36 UTC, EliteAsian123 requested changes

2024-07-23 20:36 UTC, EliteAsian123 commented on Assets/Script/Menu/DifficultySelect/DifficultySelectMenu.cs
> +                CreateItem(Localize.Key("Menu.DifficultySelect.Header.Instrument"),
It might be worth making this into `CreateLocalizedItem` like in the music library popup

2024-07-23 20:36 UTC, EliteAsian123 commented on YARG.Core
These core changes aren't required for the PR!

2024-07-24 03:35 UTC, Purplo-cf commented on Assets/Script/Menu/DifficultySelect/DifficultySelectMenu.cs
> +                CreateItem(Localize.Key("Menu.DifficultySelect.Header.Instrument"),
I started going down that route here and the added complexity for the menu items compared to `PopupMenu` make that tough without making more drastic changes. We would need different overloads for every combination of header and body text needing or not needing localization, or header doesn't exist, etc.

I did add new `CreateLocalizedHeader` and `CreateLocalizedAction` methods so that the hard-coded addresses for `Menu.DifficultySelect.Header|Action` are only in here once. These are still getting passed to a `CreateItem` that doesn't handle localization.

Will that work for adding support to this menu?

2024-07-29 02:57 UTC, merged