Remove the 70% scaling limiter on song stems
YARC-Official/YARG pull request #829
Opened 2024-07-21 14:45 UTC by sonicfind

+ Some adjustments to simplify compression in with concern to whole mixes

2024-07-22 19:18 UTC, EliteAsian123 requested changes

2024-07-22 19:18 UTC, EliteAsian123 commented on Assets/Script/Audio/Bass/BassAudioManager.cs
> +            int CompressorFX = BassHelpers.AddCompressorToChannel(mixerHandle);
Is this supposed to be a local variable, or is it supposed to reference the field? If it's the former, make sure it use `camelCase`.

2024-07-22 19:31 UTC, sonicfind commented on Assets/Script/Audio/Bass/BassAudioManager.cs
> +            int CompressorFX = BassHelpers.AddCompressorToChannel(mixerHandle);
ah yea. I copied and pasted

2024-07-23 20:33 UTC, EliteAsian123 approved these changes

2024-07-31 06:07 UTC, merged