Music Library UX improvements
YARC-Official/YARG pull request #830
Opened 2024-07-22 20:15 UTC by Purplo-cf

- Go To Section popup will now combine entries for Artist/Album/Charter/Artist - Album sorts that begin with either digits or symbols. The logic for creating these groupings will only be run once per song cache build.
- LINQ queries for creating Go To Section shortcuts will only need to run once per Search/Filter/Sort change.
- Sort By and Go To Section popup actions will not be displayed if there are no SortHeaderViewType instances in the library (e.g., results from typing in search field)
- Changing Sort By type while highlighting a song in the Recommended Songs section will now jump to that song's position in the main library instead of staying in the recommended section.

2024-07-22 23:12 UTC, Purplo-cf commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +        private IEnumerable<IGrouping<string, (ViewType, int)>> _shortcutQuery;
Is there a way to create an alias for `IEnumerable<IGrouping<string, (ViewType, int)>>` that I can use as a type? It would be great if we could just call this `CategoryGroupQuery` instead.

2024-07-23 01:55 UTC, sonicfind requested changes

2024-07-23 01:55 UTC, sonicfind commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +                   .GroupBy(g => ((SortHeaderViewType) g.Item1).ShortcutName);
Been meaning to do this, but it'd be beneficial if we manually constructed the container. The current way is done relies on a functionality that isn't immediately obvious. Its not really communicated clearly that `Select` can return the index of the value alongside the value.

We could instead just hold a `List<(string, int)>`, dodging all the need for these interfaces and wack memory & performance degradations. Only needs a for loop. The condition for whether to add a new node would simply equate to `list.count == 0 || list[^1].Group != curr.Group`

2024-07-23 01:55 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +        }
Don't know why you're using strings when we have the enums

2024-07-23 01:55 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +            }
Again, don't do this in the constructor *at all.* The constructor should just take the string Group variable directly. That's it. Anything else complicates other parts of the system that may attempt to use the type.

2024-07-23 01:55 UTC, sonicfind commented on Assets/Script/Song/SongSearching.cs
> +            bool createCategoryGroups = SongContainer.AttributeShouldBeGrouped(SettingsManager.Settings.LibrarySort.ToString());
Case and point: don't do this *whatsoever*. All the work was done already by SongContainer. Doing it again for every category in the search is unnecessary/wasteful. Just pass the same category string to the new nodes.

2024-07-23 01:55 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +        }
And there's a general reason why I specified to keep it scoped to `FillContainers()`. You mentioned that there *may* be a point where you'd use this outside of that.

But that's an assumption, and in doing so, you were tempted to still use this in an additional context where it was not needed. It's generally preferred to keep very specific non-general functionality scoped to where it is directly used if it's only used in one spot. Only once you come across a situation where having this accessible outside the class would be necessary should you publicize it.

Don't pollute a namespace with extra functionality based on if you *could* use it elsewhere but rather if you *need* to use it. And currently, we don't.

2024-07-23 01:55 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +                bool createCategoryGroups = AttributeShouldBeGrouped(attribute.ToString());
Your prior iteration with passing a bool to the Convert functions was the better option. Resorting to comparing by strings is usually not a good move.

2024-07-23 01:55 UTC, sonicfind commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +        private IEnumerable<IGrouping<string, (ViewType, int)>> _shortcutQuery;
See my comment on `GetShortcuts()`

2024-07-23 01:55 UTC, sonicfind commented on Assets/Script/Menu/MusicLibrary/ViewTypes/SortHeaderViewType.cs
> +        public SortHeaderViewType(string headerText, int songCount, string shortcutName = null)
This will never be null

2024-07-26 02:34 UTC, sonicfind requested changes
Sorry I keep dumping more on ya.

2024-07-26 02:34 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +                return genreName;
This being in the `Convert` function directly makes the interface for calling it much simpler. If you were to fix the `null` issue while still going with passing functions, you'd essentially need to pass a new instance of a function that would just return the string that was passed into it for the attribute types that don't use shortcuts. Additionally, it'd need to be the the non-formatless form (as they'd all be unique anyways).

2024-07-26 02:34 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +                    _sortDatesAdded[index++] = new(dateTime.ToLongDateString(), node.Value.ToArray(), dateTime.ToString("MMMM yyyy"));
Use `"y"` as the ToString format. That generates the month and year.

Also, `node.Key` is already a temporary local due to how the `Dictionary` enumerator works with `KeyValuePair`, so making a separate one for DateTime is just extra work.

2024-07-26 02:34 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +                    string key = node.Key.Str;
SortString has a operator that auto grabs `Str`. Not necessarily telling you to swap back, but just saying if you weren't already aware.

2024-07-26 02:34 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +            static SongCategory[] Convert(SortedDictionary<SortString, List<SongEntry>> list, Func<string, string> GenerateGroupName = null)
Now, there *is* a method to using a function instead that would be more fine in my eyes, but that requires some unsafe shenanigans here (and would start getting pretty ugly maintainability-wise). My main concern is trying to dodge needless GC heap allocations of function objects, which a boolean does not do.

2024-07-26 02:34 UTC, sonicfind commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +            Shortcuts = new();
Don't reallocate new lists. Call `Clear()` instead.

2024-07-26 02:34 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +        public SongCategory(string category, SongEntry[] songs, string categoryGroupName = null)
Essentially, there shouldn't be any situation where this is `null` *except* for "Search Results", since that doesn't even get used to begin with. It'd be best to take off the parameter default.

2024-07-26 03:13 UTC, Purplo-cf commented
> Sorry I keep dumping more on ya.

Keep it coming lol

I really appreciate you taking the time to analyze this, I'm learning a lot!

2024-07-27 14:42 UTC, sonicfind requested changes

2024-07-27 14:42 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +            static SongCategory[] Convert(SortedDictionary<SortString, List<SongEntry>> list, bool capitalizeFirstChar = false, bool createCategoryGroups = false)
Revert back to passing the SortAttribute instead of the `capitalizeFirstChar` boolean. After this PR, there is something else I need to add that relies on a specific sort.

2024-07-27 14:42 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +                            difficulty.Value.ToArray(), difficulty.Key.ToString());
The category name and shortcut need to be the same for instruments.

2024-07-27 14:42 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +                    if (capitalizeFirstChar)
Also, `attribute == SongAttribute.Genre && key.Length > 0 && char.IsLower(key[0])` was very important. It'll error out in certain situations without it. One of the oldest song scanning bugs we had.

2024-08-01 05:25 UTC, sonicfind requested changes
Some final touches for after you rebase the branch on top of some recent adjustments.

2024-08-01 05:25 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +
Need a special case to handle strings of zero length - preferably, just have it return `string.empty`. If you don't, `[0]` throws.

2024-08-01 05:25 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +                    return ".";
Return the character itself instead of `.`. The number of characters that'll appear outside the usual range isn't enough in the normal case to warrant this level of truncation (and also means non-Ascii characters can't be shown).

2024-08-01 05:25 UTC, sonicfind commented on YARG.Core
During the rebase, try to make sure the YARG.Core update is taken out your PR. It'd be an accidental downgrade.

2024-08-01 16:44 UTC, merged