Add Active Players and Bots displays to Status Bar
YARC-Official/YARG pull request #841
Opened 2024-08-05 05:16 UTC by thomeval

This PR adds two displays to the top Status Bar to display the currently active players, as well as the number of active bot profiles. These can be toggled in the Settings menu using the "Show Active Players" and "Show Active Bots" options.

![image](https://github.com/user-attachments/assets/d3bd8865-32bb-410a-a87f-f477957a18dc)

Notes:

- Show Active Players is enabled by default. Show Active Bots is not.
- Only the number of active bots is shown, since their names are probably not useful.
- The active bots display is hidden automatically if no bot profiles are active (similar to the Battery status display).
- When 1 to 3 players are connected, their instrument icons and profile names are shown.
- When 4 or more players are connected, only their instrument icons are shown.
- However, when no players are connected (including bots), the active players list will instead show a "No profiles active" message.
- The current implementation is not very efficient, as it Destroys and Instantiates prefabs on every update (once a second). Advice on how to address this (or leave it as-is) is welcome.

2024-08-05 18:40 UTC, EliteAsian123 requested changes
Thanks for the PR!

> The current implementation is not very efficient, as it Destroys and Instantiates prefabs on every update (once a second). Advice on how to address this (or leave it as-is) is welcome.

What you can do is, instead of checking every second, you can only when there are changes to active players. This is probably best done in the `PlayerContainer` class, and there is even [a method that gets called whenever there are player changes](https://github.com/YARC-Official/YARG/blob/8eb600f56c3a6c43eb764235b04e4c1af3586375/Assets/Script/Player/PlayerContainer.cs#L137). You can add on to this method and call something within `StatsManager` that then updates the active players only when there are changes. This would be WAY more efficient since creating and destroying objects in Unity is very expensive.

I've also left some comments on the code changes, however, I'll look into it more deeply once the changes are made. Thanks!

2024-08-05 18:40 UTC, EliteAsian123 commented on .editorconfig
Were these changes intended to be a part of this PR?

2024-08-05 18:40 UTC, EliteAsian123 commented on Assets/ActivePlayerListItem.cs
> +        private TextMeshProUGUI _PlayerNameText;
Should be `_playerNameText`

2024-08-05 18:40 UTC, EliteAsian123 commented on Assets/ActivePlayerList.cs
> +        public GameObject PlayerNamesPrefab;
These can all be made into private `SerializeField`s

2024-08-05 18:40 UTC, EliteAsian123 commented on Assets/ActivePlayerList.cs
> +        public int MaxShownPlayerNames = 3;
Same with this, or turn it into a constant

2024-08-05 18:40 UTC, EliteAsian123 commented on Assets/Script/Menu/Persistent/StatsManager.cs
> +        private int _activeBotCount => PlayerContainer.Players.Count(p => p.Profile.IsBot);
Properties should be name like this: `ActiveBotCount`

2024-08-05 18:40 UTC, EliteAsian123 commented on Assets/Script/Menu/Persistent/StatsManager.cs
> +                _ => throw new Exception("Unreachable.")
Switch case formatting was removed

2024-08-06 04:09 UTC, thomeval commented on .editorconfig
Yes. The one change I needed to add was `csharp_prefer_braces = false:suggestion` , or VS would "fix" all the one-liner if statements. The rest were added automatically once I opened the .editorconfig file and I left them at defaults, but I think it might be good to have these all here for consistency, especially if other team members are using different IDEs.

2024-08-06 04:23 UTC, thomeval commented on Assets/ActivePlayerListItem.cs
> +        private TextMeshProUGUI _PlayerNameText;
Oops. I'll add an .editorconfig rule for this.

2024-08-06 04:28 UTC, thomeval commented on Assets/Script/Menu/Persistent/StatsManager.cs
> +        private int _activeBotCount => PlayerContainer.Players.Count(p => p.Profile.IsBot);
I'll add an .editorconfig rule for this.

2024-08-06 10:07 UTC, thomeval commented
Thanks for the feedback. I'll make the changes discussed above and get back to you.

2024-08-06 12:34 UTC, thomeval commented on Assets/ActivePlayerList.cs
> +        public GameObject PlayerNamesPrefab;
Resolved

2024-08-06 12:34 UTC, thomeval commented on Assets/Script/Menu/Persistent/StatsManager.cs
> +        private int _activeBotCount => PlayerContainer.Players.Count(p => p.Profile.IsBot);
Resolved

2024-08-06 12:34 UTC, thomeval commented on Assets/Script/Menu/Persistent/StatsManager.cs
> +                _ => throw new Exception("Unreachable.")
Resolved

2024-08-06 12:34 UTC, thomeval commented on Assets/ActivePlayerList.cs
> +        public int MaxShownPlayerNames = 3;
Resolved

2024-08-06 12:37 UTC, thomeval commented
I've updated this branch with the requested changes, and did a quick test to see if everything is still working as it should. I've needed to update ProfileListMenu as well in order to fix a bug where player instrument icons weren't updating when players change their Game Mode.

2024-08-08 20:41 UTC, EliteAsian123 commented on .editorconfig
The problem with that is it looks like it's adding incorrect keys at the bottom (I may be wrong) for non-C# files, but the rules appear to be for C#.

2024-08-08 21:39 UTC, EliteAsian123 commented on .editorconfig
Oh also, some of the rules are incorrect/changed such as this one:
![image](https://github.com/user-attachments/assets/e37fc2cf-71bb-45d2-a3f4-9d7311dd0f89)

2024-08-08 22:09 UTC, EliteAsian123 requested changes
Hello, thanks for the changes!

I did a little more of a thorough review this time so there is a lot. Sorry about that.

Please let me know if you need any assistance! Thanks.

2024-08-08 22:09 UTC, EliteAsian123 commented on Assets/ActivePlayerList.cs
> +        public void UpdatePlayerList(IReadOnlyCollection<YargPlayer> players)
This method only has one use, which provides the static field `PlayerContainer.Players`. Instead, this parameter should be removed and `PlayerContainer.Players` should be used directly instead (since I don't think there's a case where a different list is used).

2024-08-08 22:09 UTC, EliteAsian123 commented on Assets/Script/Player/PlayerContainer.cs
> +            StatsManager.Instance.UpdateActivePlayers();
This method should be renamed to something more generic such as `ActiveProfilesChanged` or something like that

2024-08-08 22:09 UTC, EliteAsian123 commented on Assets/Script/Menu/ProfileList/ProfileListMenu.cs
> +            StatsManager.Instance.UpdateActivePlayers();
This is kinda hacky but there isn't really another way to watch for game mode changes, so it should be fine for now

2024-08-08 22:09 UTC, EliteAsian123 commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +            public ToggleSetting ShowActivePlayers { get; } = new(true, ShowActivePlayersCallback);
This setting shouldn't be enabled by default in my opinion, since none of the other stats are by default.

2024-08-08 22:09 UTC, EliteAsian123 commented on .editorconfig
(see comments on the initial review of this file)

2024-08-09 05:41 UTC, thomeval commented on .editorconfig
That's odd. It works fine on my end:
![image](https://github.com/user-attachments/assets/60f4edde-0200-431d-9dc6-175bba12e216)

I will look into this some more, but I suspect that the two rules in place for "private fields" and "constants" are clashing with each other, and different IDE setup have different ways of prioritizing which rule applies to private constants.

2024-08-09 14:04 UTC, thomeval commented on .editorconfig
Okay, I suggest we take the .editorconfig changes out of this PR. I'd rather not have this issue delay things, and I can always submit a separate PR for that later.

2024-08-09 14:12 UTC, thomeval commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +            public ToggleSetting ShowActivePlayers { get; } = new(true, ShowActivePlayersCallback);
Fair point. I don't necessarily agree, but I'll defer to your judgement on this one.

2024-08-10 04:40 UTC, thomeval commented on Assets/ActivePlayerListItem.cs
> +        private Sprite[] _gameModeIcons = new Sprite[0];
During testing I found this change caused a regression. I'll DM you to discuss this further.

2024-09-04 05:43 UTC, closed without merging