Added note speed reduction by difficulty
YARC-Official/YARG pull request #845
Opened 2024-08-10 21:04 UTC by Hubbubble1

This PR adds a note speed reduction for all players/bots playing charts at a lower difficulty. This can be toggled in the Settings menu using the "Reduce Note Speed by Difficulty" option.

[[video]](https://www.youtube.com/watch?v=ucWM8VI1ZhE)

Notes:
- Reduce Note Speed by Difficulty is enabled by default.
- The vocal track is not affected by this option: it remains the same speed on all difficulties.
- The specified note speed is applied on Expert and Expert+, and the note speeds are reduced by 25% for each difficulty down (X->H, H->M, M->E). These reductions in speed are similar to those in the Rock Band series.

2024-08-12 21:26 UTC, EliteAsian123 requested changes
One quick change and this should be good to go!

2024-08-12 21:26 UTC, EliteAsian123 commented on Assets/Script/Gameplay/Player/BasePlayer.cs
> +                    return Player.Profile.NoteSpeed * Player.Profile.CurrentDifficulty.NoteSpeedScale() / (float) Player.EngineParameterOverride.SongSpeed;
`Player.Profile.NoteSpeed * Player.Profile.CurrentDifficulty.NoteSpeedScale()` is duplicated everywhere so it's probably best that this is put into a local variable called `noteSpeed` or something like that.

2024-08-13 03:05 UTC, Hubbubble1 commented on Assets/Script/Gameplay/Player/BasePlayer.cs
> +                    return Player.Profile.NoteSpeed * Player.Profile.CurrentDifficulty.NoteSpeedScale() / (float) Player.EngineParameterOverride.SongSpeed;
Done; let me know if the change I made is in the right style

2024-08-13 04:42 UTC, EliteAsian123 approved these changes

2024-08-13 04:42 UTC, merged