Datastream implementation (for real this time)
YARC-Official/YARG pull request #849
Opened 2024-08-13 00:26 UTC by TheFatBastid

Created a UDP data stream that YARG will output on port 36107. This data stream contains information on virtually everything YARG is doing at the moment. This replaces all built-in IRL lighting protocols: Stage Kit, DMX, RB3E, HUE, etc. These are now all handled by the external program, YALCY. (all related settings removed as well)

2024-08-13 22:03 UTC, RileyTheFox requested changes
I tested this out and it worked perfectly after I built YALCY (I don't have any lighting hardware so I was just going off of the visualiser in the app)

Profiled it as I am concerned about performance with a feature like this and did not notice any memory allocations during gameplay or high CPU usage which is good.

I am however very concerned about the way the packet construction is done, as well as the fact that *everything* is using an enum. The packet structure should not be determined by values in an enum. This is not a maintainable solution if it were to be added to in the future. It should be a *structure* (struct or class) with fields for the data that will be in the packet which is then serialized to binary.

Something along the lines of this:
```csharp
public struct LightingMessage
{
    public float BeatsPerMinute;
    public LightingEvent LightingCue;
    etc...
}
```

this Message type is then serialized to binary and sent off over the network.

I haven't put too many review comments because I'd just be repeating the same thing. My comments are highlighted usually at the first instance I came across something, but what its saying can be applied to many other places too.

I want this to be done right because if done correctly, this data stream setup can be reused for sending packets for lots of other game information beyond lighting. So if its done correctly now there's less work to do for those features down the line.

2024-08-13 22:03 UTC, RileyTheFox commented on Assets/Script/Integration/MasterLightingController.cs
> +                _sendClient.Send(_dataPacket, _dataPacket.Length, IPAddress.ToString(), PORT);
Cache this ToString result somewhere. The IP address is readonly so the hostname is not going to change so this should not need to be called every time.

I couldn't see if this was allocating anything but its best to be safe and just cache the result anyway.

2024-08-15 04:06 UTC, TheFatBastid commented
Ready for round two review. Don't merge as I still need to redo the YALCY side to match this.

2024-08-17 15:19 UTC, RileyTheFox requested changes
Big improvements over the first iteration but still some way to go. You've introduced allocation every time a packet is created and sent (which is 88 times a second!) which is bad for gameplay as it increases the likelihood the Garbage Collector stalls the game causing lag spikes.

You also used BinaryFormatter, which is a huge no no. See the comment on that for details.

2024-08-17 15:19 UTC, RileyTheFox commented on Assets/Script/Integration/MasterLightingGameplayMonitor.cs
> +                return (int) list[listIndex].Pitch;
Pitch is a `float`, is the cast to int necessary? Data is being lost with this cast

2024-08-17 15:19 UTC, RileyTheFox commented on Assets/Script/Integration/MasterLightingGameplayMonitor.cs
> +                MasterLightingController.MLCCurrentHarmony2Note = (byte)Harmony2Note;
The `Pitch` value from VocalEventChecker has now gone from a 32 bit float, to a 32 bit integer to an 8 bit integer. What is with casting it down so much?

2024-08-17 15:19 UTC, RileyTheFox commented on Assets/Script/Integration/MasterLightingGameplayMonitor.cs
> +            return -1;
Because this value gets casted to a byte in the end, this will end up as `255` because a byte is not signed. Is that intentional?

2024-08-17 15:19 UTC, RileyTheFox commented on Assets/Script/Integration/MasterLightingController.cs
> +                if (value.Type != LightingType.Keyframe_Next && value.Type != LightingType.Keyframe_Previous &&
Consider using pattern matching here to make it easier to read.

```csharp
if (value.Type is not (LightingType.One or LightingType.Next or etc etc))
```

2024-08-17 15:19 UTC, RileyTheFox commented on Assets/Script/Integration/MasterLightingController.cs
> +            switch (platform)
Running this each time is unnecessary as the platform is never going to change during runtime. Use the `#if #elif #else #endif` preprocessors and check for unity symbol definitions for each platform

[Preprocessor Directives](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives)

[Unity Platform Scripting Symbols](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html)

You only need to use the editor/standalone for Windows, OSX and Linux.

Look at this [example](https://github.com/YARC-Official/YARG/blob/86bba9fee15c92d80b2afa96fd93091dc85c5825/Assets/Script/Audio/Bass/BassAudioManager.cs#L345) from YARG to see how they are used.

2024-08-18 21:08 UTC, TheFatBastid commented on Assets/Script/Integration/MasterLightingGameplayMonitor.cs
> +                MasterLightingController.MLCCurrentHarmony2Note = (byte)Harmony2Note;
Old dmx code and thought process, as it was to fit it in into 1 dmx channel byte, and was 'close enough' but that isn't applicable anymore, will fix it.

2024-08-18 23:46 UTC, TheFatBastid commented
Ready for round three!

2024-08-24 15:02 UTC, RileyTheFox requested changes

2024-08-24 15:02 UTC, RileyTheFox commented on Assets/Script/Integration/MasterLightingController.cs
> +            message.Header = 0x59415247; // Y A R G
If you're sending a blank packet to turn everything off, just recreate the LightingMessage object. Saves you having to retype every variable within the message type just to set it to 0.

2024-08-24 15:02 UTC, RileyTheFox commented on Assets/Script/Integration/MasterLightingController.cs
> +        public static LightingMessage message = new LightingMessage();
These should be private, and also do not need to be static from what I can tell. Rename appropriately, `_privateVar`

2024-08-25 23:15 UTC, TheFatBastid commented
Ready for round four!

2024-08-30 23:48 UTC, closed without merging