Display unique needle graphics for each Vocals player (up to 7)
YARC-Official/YARG pull request #853
Opened 2024-08-17 08:34 UTC by thomeval

This PR adds unique vocal needle graphics for each vocals player, based on the order their profiles joined/connected. This uses the existing needle sprites, although in a different order to maximize visibility.

I've chosen the sprites shown below for the first three vocalists, as it provides at least some visibility to each player even in the worst case scenario where all three are on top of each other. 
![YARG-3pVocals](https://github.com/user-attachments/assets/7805f47d-b622-4016-95ab-3f943d7d0cbd)

And this is what it looks like with six vocalists, two per harmony part. If there are more than seven vocalists, each needle graphic will be reused, in order.

![YARG-6pVocals](https://github.com/user-attachments/assets/1552a6ad-54b3-4b83-96e5-16c2888847ed)

2024-08-26 20:37 UTC, EliteAsian123 requested changes
Hello! Thanks for the PR and sorry for the late review.

Just a few very minor things and this should be good to merge! Thank you!

2024-08-26 20:37 UTC, EliteAsian123 commented on Assets/Script/Gameplay/Player/VocalsPlayer.cs
> +            _needleRenderer.material = Addressables.LoadAssetAsync<Material>(materialPath).WaitForCompletion();
The vocal  needle addressable group name can be simplified a bit (to something like `VocalNeedle/N`), just so the naming fits in with the other addressables

2024-08-26 20:37 UTC, EliteAsian123 commented on Assets/Script/Gameplay/Player/VocalsPlayer.cs
> +            VocalPlayerIndex = vocalIndex;
Is this property needed? It looks like it's only used to determine the sprite at the moment.

2024-08-26 20:37 UTC, EliteAsian123 commented on Assets/Script/Gameplay/Player/VocalsPlayer.cs
> +            var needleIndex = (VocalPlayerIndex % NEEDLES_COUNT) + 1;
The parentheses are not needed here

2024-08-27 05:57 UTC, thomeval commented on Assets/Script/Gameplay/Player/VocalsPlayer.cs
> +            var needleIndex = (VocalPlayerIndex % NEEDLES_COUNT) + 1;
Would you mind if we kept these parentheses? We've all memorized the order of operations by this point, but I feel like this line is easier to read with them. I'd understand if we'd rather want to be consistent throughout though.

2024-08-28 09:41 UTC, thomeval commented
Okay, this is ready for another review.

2024-08-29 03:29 UTC, merged