Stem muting and practice countdown bugfixes
YARC-Official/YARG pull request #856
Opened 2024-08-18 18:51 UTC by Purplo-cf

Fix for this issue on the discord:
https://discord.com/channels/1086048856678084609/1270492316569702512

Also found and fixed a weird countdown thing in Practice mode while I was testing this

2024-08-18 19:45 UTC, Purplo-cf commented
Took care of another low-hanging bugfix in the Discord while I'm here:
https://discord.com/channels/1086048856678084609/1273906333007089685

2024-08-26 21:02 UTC, EliteAsian123 requested changes

2024-08-26 21:02 UTC, EliteAsian123 commented on Assets/Script/Gameplay/Player/Vocals/VocalTrack.cs
> +                _changeEndTime = _changeStartTime;
It seems like this "instant change range" set of code is used in a couple of places now, so if you could make an argument on the `ChangeRange` method that changes the range instantly, that'd be cool! If not, it's fine for now.

2024-08-26 21:03 UTC, EliteAsian123 commented
Sorry for the late review, and thanks for the PR!

I've reviewed the PR above. Let me know if you have any questions.

Thanks!

2024-09-03 20:07 UTC, closed without merging