Add guidelines to vocal highway
YARC-Official/YARG pull request #857
Opened 2024-08-20 04:48 UTC by thomeval

This PR adds horizontal guidelines to the background of the vocal highway, for both solo and harmony vocals. The guidelines are scaled and shifted according to the vocal range of notes on the highway. Range shifts are supported as well. In order to fix issues with notes not being aligned with the guidelines, some changes were made to the code that positions vocal notes as well.

![image](https://github.com/user-attachments/assets/c6b17fec-7da9-40dc-9c06-0866417ac995)

Note that unlike RB3, the guidelines will always show the C-Major scale (C,E,G,C), and will ignore the song's key. This is considered out of scope for this PR, it we would need to add support for the (vocal_tonic_note) and (song_tonality) fields, which is generally only found in newer RBCON files and RBHP upgrades.

2024-08-26 21:19 UTC, EliteAsian123 requested changes
Overall pretty good!

Just a few minor nitpicks and this should be good to go!

2024-08-26 21:19 UTC, EliteAsian123 commented on Assets/Script/Gameplay/Player/Vocals/VocalTrack.cs
> +            _harmonyGuidelineRenderer.material.mainTextureScale = new Vector2(1, scale);
Repeated access of the same material is quite expensive. Instead, these values should probably be cached somewhere.

2024-08-26 21:19 UTC, EliteAsian123 commented on Assets/Script/Gameplay/Player/Vocals/VocalTrack.cs
> +        private const float RANGE_PADDING_PERCENT = 0.1f;
Use summary comments for these:
```
/// <summary>
/// Like this
/// </summary>
```

2024-08-26 21:19 UTC, EliteAsian123 commented on Assets/Script/Gameplay/Player/Vocals/VocalTrack.cs
> +            float rangeMin = Math.Min(rangeMiddle - (MINIMUM_SEMITONE_RANGE / 2), range.MinimumPitch);
Remove the empty space at the top of this method

2024-08-26 21:19 UTC, EliteAsian123 commented on ProjectSettings/ProjectSettings.asset
These file changes probably weren't intended

2024-08-26 21:19 UTC, EliteAsian123 commented on Assets/Art/Materials/Gameplay/Visual/VocalTrackGuidelines.mat
In my opinion, this texture is still a little too jarring. If the transparency could be toned down a bit more I think that'd be better

2024-08-27 14:27 UTC, thomeval commented on Assets/Script/Gameplay/Player/Vocals/VocalTrack.cs
> +            float rangeMin = Math.Min(rangeMiddle - (MINIMUM_SEMITONE_RANGE / 2), range.MinimumPitch);
This was changed due to incoming changes from the base branch, so it should be resolved now.

2024-08-28 04:25 UTC, thomeval commented
Alright, this one is ready for another review.

2024-08-29 03:32 UTC, EliteAsian123 commented
The code looks good to me, I'll check in game for the texture tomorrow!

2024-09-03 15:50 UTC, EliteAsian123 approved these changes

2024-09-03 15:51 UTC, merged