Sorted Profiles List
YARC-Official/YARG pull request #858
Opened 2024-08-22 15:03 UTC by thomeval

This PR adds sorting and groups to the Profiles list. All profiles are now grouped into three groups:
- Active profiles. These are profiles that are currently connected, both players and bots.
- Players. These are human profiles that aren't currently being used.
- Bots. These are bot profiles that aren't currently being used.

All entries in the above groups are sorted alphabetically as well.

![image](https://github.com/user-attachments/assets/9d4b302e-ffbb-4c76-82a5-3f6cf004ef08)

Note to the reviewer: For the group headings, I borrowed the Prefab used for headers on the Music Library, though I needed to add a Component to them to be able to set their text at runtime.

2024-09-03 16:22 UTC, EliteAsian123 requested changes
For some reason I'm having trouble loading into the game with this PR. Did you accidently leave the profile list enabled in the menu scene? Because of this I can't really test it, but I'll will comment on what I noticed below.

Thanks for your patience!
![image](https://github.com/user-attachments/assets/c2ea1de8-eacd-4746-8453-f301c2f346ec)

2024-09-03 16:22 UTC, EliteAsian123 commented on Assets/Script/Menu/ProfileList/ProfileListMenu.cs
> +            headerGo.GetComponent<ListHeader>().Text = header;
Since you're doing `GetComponent` here anyways, it may be easier to just do `GetComponentInChildren<TextMeshProUGUI>().text = ...` instead, and remove the new script.

2024-09-03 16:22 UTC, EliteAsian123 commented on Assets/Script/Menu/ProfileList/ProfileListMenu.cs
> +            AddListGroup("Bots", otherProfiles.Where(e => e.IsBot));
The more efficient way would be to loop through all of the profiles using just a normal foreach loop. Will that be more readable? Probably about the same. It's up to you if you wanna do that instead.

2024-09-04 05:03 UTC, thomeval commented on Assets/Script/Menu/ProfileList/ProfileListMenu.cs
> +            AddListGroup("Bots", otherProfiles.Where(e => e.IsBot));
I think that would be tricky, since there are two collections at play here (`PlayerContainer.Profiles` and `PlayerContainer.Players` ). You'd also have to implement the sorting manually if you really wanted to avoid using LINQ. It would be more efficient, but by how much? I haven't run it through a profiler, but I'm guessing we're probably talking less than a 1ms difference (assuming you have less than a thousand profiles), and be far less relevant that the `Instantiate()` calls that are used in `AddListGroup()`.

2024-09-04 05:37 UTC, thomeval commented
@EliteAsian123 Sorry about that. I've disabled the profile list, so its working again. I've also updated the branch to remove the ListHeader script as suggested.

2024-09-06 01:34 UTC, EliteAsian123 reviewed
Thanks for doing that!

One thing I think would be good is to disable the header when there are no items in, as I think having two headers in a row is kinda weird:
![image](https://github.com/user-attachments/assets/426f8d25-b397-476d-9f46-040ebf60752c)

Other than that (and the one review comment below) this is pretty much good to go!

Sorry for the wait!

2024-09-06 01:34 UTC, EliteAsian123 commented on Assets/Script/Menu/ProfileList/ProfileListMenu.cs
> +            AddListGroup("Bots", otherProfiles.Where(e => e.IsBot));
The header text should be localized (with `Localize.Key`)

2024-09-06 05:54 UTC, thomeval commented
Okay, I've pushed changes to the branch that resolves those two issues.

2024-09-06 15:05 UTC, EliteAsian123 approved these changes

2024-09-06 15:05 UTC, merged