Stem-muting, countdown, and notification bugfixes
YARC-Official/YARG pull request #866
Opened 2024-09-03 20:18 UTC by Purplo-cf

-Fix for stem-muting while SP reverb is in the process of fading in or out
-Fix for countdowns appearing right before the start of a practice section where the earlier notes in the chart are artificially removed
-Added countdowns back into the vocal track prefab after they were taken out
-Fixed TrackView notifications not appearing by re-checking the box that makes them active by default.

This is a modified version of my PR from last month, rebased to the latest changes. I saw that Nathan fixed vocal range changes in practice mode so I took that out.

Regarding the practice mode countdown fix - I changed how it's structured in Unity so that countdowns are active by default with an alpha of 0 to keep them hidden. This way, `Awake()` is called at the start of a song and the script can detect if it's in practice mode.

2024-09-05 20:59 UTC, Purplo-cf commented
Reference for @sonicfind 's thoughts on the stem muting fix. EA was looking additional input on the last version of this PR
https://discord.com/channels/1086048856678084609/1086052453801283624/1274528287548506165

2024-09-05 21:04 UTC, EliteAsian123 requested changes
Looks good to me!

As of now though, we require braces on if statements (expect in places where it would benefit the clarity of the code). After those are added, this will be merged!

2024-09-05 21:04 UTC, EliteAsian123 commented on Assets/Script/Audio/Bass/BassStemChannel.cs
> +                YargLogger.LogFormatError("Failed to set stream volume: {0}!", Bass.LastError);
Here

2024-09-05 21:04 UTC, EliteAsian123 commented on Assets/Script/Audio/Bass/BassStemChannel.cs
>                  YargLogger.LogFormatError("Failed to set reverb volume: {0}!", Bass.LastError);
Here

2024-09-07 02:23 UTC, Purplo-cf commented
Braces added and refactored to the latest changes!

2024-09-07 16:39 UTC, merged