Feature/active players list
YARC-Official/YARG pull request #867
Opened 2024-09-04 05:42 UTC by thomeval

This PR adds two displays to the top Status Bar to display the currently active players, as well as the number of active bot profiles. These can be toggled in the Settings menu using the "Show Active Players" and "Show Active Bots" options.

Notes:

- Replaces PR #841
- Requires YARG.Core PR [#209](https://github.com/YARC-Official/YARG.Core/pull/209)
-  Neither of the above options are enabled by default.
-  Only the number of active bots is shown, since their names are probably not useful.
-  The active bots display is hidden automatically if no bot profiles are active (similar to the Battery status display).
-  When 1 to 3 players are connected, their instrument icons and profile names are shown.
-  When 4 or more players are connected, only their instrument icons are shown.
-  However, when no players are connected (including bots), the active players list will instead show a "No profiles active" message.

2024-09-07 16:55 UTC, EliteAsian123 requested changes
Thanks for the PR!

Just a few review points and this should be good to go!

2024-09-07 16:55 UTC, EliteAsian123 commented on Assets/Script/Menu/Persistent/StatsManager.cs
> +                return;
Make sure to add braces to this

2024-09-07 16:55 UTC, EliteAsian123 commented on Assets/Script/Player/PlayerContainer.cs
> +                    profile.CurrentInstrument =  profile.GameMode.PossibleInstruments()[0];
It would be my preference to move this statement to the YARG.Core side as a method because it could be used in other applications that make use of the `YargProfile`.

2024-09-07 16:55 UTC, EliteAsian123 commented on Assets/Script/Menu/Persistent/ActivePlayerList.cs
> +            }
I believe we have an extension method for doing this called `DestroyChildern()` that can be called on the transform.

2024-09-07 16:58 UTC, thomeval commented on Assets/Script/Menu/Persistent/StatsManager.cs
> +                return;
Oh dear, what have I done?!

2024-09-08 12:55 UTC, thomeval commented
Okay, this is ready for another review.

2024-09-14 20:48 UTC, merged