Improver solo high scores, basic band high scores
YARC-Official/YARG pull request #883
Opened 2024-09-27 08:36 UTC by thomeval

This PR improves the way solo high scores are handled on the Music Library screen (and elsewhere), bringing it more in-line with RB and CH.

![image](https://github.com/user-attachments/assets/835c5e52-1e35-4100-8022-dd5efbb20d4f)

Main changes include:
- Solo high scores now only display if there is exactly one non-bot player connected.
- The Music Library will no longer display irrelevant scores. It will only display the best score for the current player, for their current instrument.
- Removed the now unnecessary instrument icon.... sort of. See below.
- The existing behaviour of showing both the best score and best percentage, even if those are from different runs, has been left intact.
- Added a FC indicator! There isn't a graphic for it yet though, so I'm reusing the instrument icon as a placeholder for now.
- The "New High Score" notification will now trigger if the given player has beaten their own personal best, not the "machine best".

This PR also introduces a basic version of band high scores, shown when there are no players, or more than one player connected:

![image](https://github.com/user-attachments/assets/da67ff59-2fad-4a53-ae03-be3dae4c9173)

These are pulled from the `GameRecord` table. Known limitations:
- Band high scores include scores obtained by only one player. I propose that we only display scores with at least two players, but we don't currently store the number of band members in the database.
- Bots are welcome to set high scores. I propose that we exclude any high score that had any bot players, but we don't currently score this in the database.

2024-09-27 08:37 UTC, thomeval commented
Not yet ready to merge. Still needs testing.

2024-09-29 05:05 UTC, thomeval commented
Ready for review.

2024-10-08 01:18 UTC, EliteAsian123 commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +        private bool _shouldDisplaySoloHighScores => PlayerContainer.Players.Count(e => !e.Profile.IsBot) == 1;
Properties should always be in `PascalCase`

2024-10-08 01:33 UTC, EliteAsian123 requested changes
Hi, sorry for the very late review, I've been very busy recently.

I've listed some styling changes below, however, there's one big thing that I want changed which is how bots are handled at the moment with band scoring. 

Bots should *never* under any circumstances have their scores saved. This wasn't really a problem before, as we only displayed individual scores, but with this change, bands with bot scores in there show up, which obviously doesn't make sense. Once we introduce band multipliers, it will make even less sense, as individual scores will be effected too.

Because of this, all band scores with bots should be completely invalidated and not saved. From the looks of it we currently do, however, I'd classify this as a bug as it really shouldn't be. 

Once this change is made, this PR looks pretty much good to me, however I haven't tested it in-game yet so I'll do that once this is fixed.

Thanks!

Edit: if this is changed then also the `PlayerContainer.Players.Count(e => !e.Profile.IsBot) == 1` wouldn't be needed and could be simplified as if a bot is in your band, you're still technically in a band and not playing solo.

2024-10-08 01:33 UTC, EliteAsian123 commented on Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
> +        private bool _shouldDisplaySoloHighScores => PlayerContainer.Players.Count(e => !e.Profile.IsBot) == 1;
Properties should always be in `PascalCase`.

2024-10-08 01:33 UTC, EliteAsian123 commented on Assets/Script/Menu/MusicLibrary/ViewTypes/SongViewType.cs
> +        {
Make sure to strip extra whitespace

2024-10-08 01:33 UTC, EliteAsian123 commented on Assets/Script/Scores/ScoreContainer.cs
> +
Remove this empty line

2024-10-08 01:33 UTC, EliteAsian123 commented on Assets/Script/Scores/ScoreContainer.cs
> +
Remove this empty line

2024-10-21 16:54 UTC, EliteAsian123 commented
#898 has been merged, so if you can update this PR to account for this, I'll review it and merge it. Thanks!

2024-10-22 08:47 UTC, thomeval commented
@EliteAsian123 Okay, this PR has been updated with the latest dev branch and is ready to review.

2024-10-23 00:10 UTC, merged