Always On Drum SFX
YARC-Official/YARG pull request #889
Opened 2024-10-04 03:26 UTC by nameonascreen

Added an "Always-On Drum SFX" toggle.

Not the best implementation but will do as a temporary method.. This is global and not per-profile

Feel free to deny, I'm terrible at coding stuff and already know this is bad lol.

2024-10-04 03:56 UTC, sonicfind requested changes

2024-10-04 03:56 UTC, sonicfind commented on Assets/Script/Settings/SettingsManager.Settings.cs
> +            public ToggleSetting AlwaysOnDrumSFX { get; } = new(true);
Set to `false` by default to match *expected* behavior of the feature.

2024-10-04 03:56 UTC, sonicfind commented on ProjectSettings/ProjectSettings.asset
> +  - {fileID: 0}
Make sure to remove changes like these before pushing. It's usually Unity being funky, but it can cause problems.

2024-10-04 03:56 UTC, sonicfind commented on Assets/Script/Gameplay/Player/DrumsPlayer.cs
> +            }
1. This breaks hit logic because of the removal of the `return` on `wasNoteHit`. That's not optional; it *has* to happen.
2. Without checking the state of `SettingsManager.Settings.AlwaysOnDrumSFX.Value` on line 147, you're forcing it to make **two** calls to `PlayDrumSoundEffect` in freestyle sections when it is set to `true`
3. 
```
if (!wasNoteHit)
{
    PlayDrumSoundEffect(action, velocity);
}
else
{
    PlayDrumSoundEffect(action, velocity);
}
```
Both branches are doing the same exact thing, so the if-else serves no purpose.
4. Make sure that the formatting of whitespace before each line matches the rest of the code. You're one "tab" (four spaces) too few on each.

2024-10-07 05:56 UTC, sonicfind requested changes

2024-10-07 05:56 UTC, sonicfind commented on Assets/Script/Gameplay/Player/DrumsPlayer.cs
> +            }
1. No reason to call `return` in both the the `if` AND the `else`. Just call return *after( the if branch, removing the `else` entirely.
2. Again, make sure that the formatting of whitespace before each line matches the rest of the code. You're one "tab" (four spaces) too few on each.

2024-10-07 05:56 UTC, sonicfind commented on Assets/Script/Gameplay/Player/DrumsPlayer.cs
> +                if (isDrumFreestyle || SettingsManager.Settings.AlwaysOnDrumSFX.Value)
Swap the two. If `SettingsManager.Settings.AlwaysOnDrumSFX.Value` is active, then it'd be always active, making the freestyle unnecessary to test for in those situations.

2024-10-07 22:36 UTC, sonicfind commented on Assets/Script/Gameplay/Player/DrumsPlayer.cs
> +                } return;
`return` needs to be in the notehit scope.

2024-10-08 00:33 UTC, nameonascreen commented on Assets/Script/Gameplay/Player/DrumsPlayer.cs
> +                } return;
Had it right the first time then, thanks.

2024-10-13 18:24 UTC, sonicfind commented on Assets/Script/Gameplay/Player/DrumsPlayer.cs
> +                    } return;
`return` on the next line

2024-10-16 16:09 UTC, EliteAsian123 approved these changes
Looks good to me

2024-10-17 00:46 UTC, sonicfind approved these changes

2024-10-17 00:49 UTC, merged