Prevent invalid high scores from being saved
YARC-Official/YARG pull request #898
Opened 2024-10-10 12:58 UTC by thomeval

This PR adds validation to Band and Solo high scores, meaning that they will be considered invalid and thus not saved when certain conditions are met. This also includes a "Band score not saved" message on the Result screen. Unfortunately, it is not possible to filter out already existing invalid high scores, so the validation rules will only apply to scores set after this PR is merged.

Currently, a band high score will be considered invalid if the Song Speed is less than 100% :
![Screenshot 2024-10-08 142841](https://github.com/user-attachments/assets/233d6bf1-65af-4805-be9c-c22277a77ca1)

Or if any bots are active:

![Screenshot 2024-10-10 141616](https://github.com/user-attachments/assets/5f82db71-4079-491e-87d5-ec5142bcf647)

It will be fairly simple to add more rules later by extending the `ScoreContainer.IsSoloScoreValid()` and `ScoreContainer.IsBandScoreValid()` methods.

**Known Limitation:**  In some circumstances, it is possible for a Band Score to be invalid, but a player's Solo Score to still be valid (for example, when playing with bots). In such cases, we should save the player score, but not the band score. Assuming there are no blockers preventing it, this will be addressed in the Solo High Score overhaul PR.

2024-10-12 20:51 UTC, EliteAsian123 requested changes
Hello! Sorry for the late review again.

After some changes below, this should be good to go!

2024-10-12 20:51 UTC, EliteAsian123 commented on Assets/Script/Menu/ScoreScreen/ScoreScreenContainer.cs
> +        public float SongSpeed;
There already exists a `SongSpeed` property in `PersistentState`, so you can just use that.

2024-10-12 20:51 UTC, EliteAsian123 commented on Assets/Script/Gameplay/GameManager.cs
> +
Please ensure you strip whitespace!

2024-10-12 20:51 UTC, EliteAsian123 commented on Assets/Script/Gameplay/GameManager.cs
> +            if (ScoreContainer.IsBandScoreValid( SongSpeed))
This check should be at the start of the function since that means all of the calculations above aren't actually used. (i.e., `if (...) return;`)

2024-10-12 20:51 UTC, EliteAsian123 commented on Assets/Script/Menu/ScoreScreen/ScoreScreenMenu.cs
> +            }
This check doesn't actually do anything because `PlayerScores` includes bots. So this is basically just checking if any profiles are in the song (which is always the case).

2024-10-12 20:51 UTC, EliteAsian123 commented on Assets/Script/Scores/ScoreContainer.cs
> +            }
This check fails if bots are sitting out, even though players that sit out don't effect the score

2024-10-12 20:51 UTC, EliteAsian123 commented on Assets/Script/Player/PlayerContainer.cs
> +        public static bool HasBots => _players.Any(i => i.Profile.IsBot);
This property is unused

2024-10-12 20:51 UTC, EliteAsian123 commented on Assets/Script/Menu/ScoreScreen/ScoreScreenMenu.cs
> +            _bandScoreNotSavedMessage.text = Localize.Key("Menu.ScoreScreen.BandScoreNotSaved");
Use the "Localize Text" component instead, and just reference the game object in the serialized field.

2024-10-12 20:51 UTC, EliteAsian123 commented on Assets/Scenes/ScoreScene.unity
![image](https://github.com/user-attachments/assets/6c9e2416-632f-4600-83a8-9aa82aaa07eb)
The text should be a child of the header and it should be anchored to the right-side for it to work on other resolutions

2024-10-12 20:51 UTC, EliteAsian123 commented
> In some circumstances, it is possible for a Band Score to be invalid, but a player's Solo Score to still be valid (for example, when playing with bots). 

For future proofing, it's probably better for this not to be a thing whenever band multipliers and stuff come into play.

2024-10-13 04:10 UTC, thomeval commented on Assets/Script/Scores/ScoreContainer.cs
> +            }
Nice catch! I completely missed that.

2024-10-16 16:07 UTC, EliteAsian123 approved these changes
The code is all good! I'm away right now so once I get back I'll test this in-game and this should be good to merge (if one of the other maintainers could do that, that could work too)

2024-10-21 16:52 UTC, merged