Customizable Highway Presets
YARC-Official/YARG pull request #905
Opened 2024-10-18 11:22 UTC by thomeval

This PR introduces a new type of preset to YARG: Highway Presets. These are used to customize the colours of the note highway. This includes the "default" colours, as well as the glow from Groove (when at max multiplier) and when Star Power is active.

This change also includes three default presets out of the box:
![YARG-HighwayPresets](https://github.com/user-attachments/assets/713905c6-620b-4ee8-8d04-39db15cedd97)
*From left to right: Default, Basic, No Groove, and a custom preset.*

Custom presets can be edited from the Settings menu:
![image](https://github.com/user-attachments/assets/98369727-a087-4db0-88f8-fe900791b78f)

2024-11-08 02:36 UTC, EliteAsian123 requested changes
Hello! Thanks for the PR, this is awesome! 

I've just requested some simple changes below. Once the YARG.Core PR is merged, you can update the YARG.Core pointer in this PR and then this can be merged as well!

2024-11-08 02:36 UTC, EliteAsian123 commented on Assets/Script/Gameplay/GameManager.cs
> +            var highwayPresets = new Dictionary<Guid, HighwayPreset>();
This variable doesn't appear to be used anymore (contents are updated, but not utilized)

2024-11-08 02:36 UTC, EliteAsian123 commented on Assets/Script/Gameplay/Visuals/TrackMaterial.cs
> +            public static Preset FromColors(System.Drawing.Color[] colors)
Instead of doing something like `FromColors`, it might be better to do something like `FromHighwayPreset` where you can directly provide the highway preset as an argument and set up the struct's values from there, instead of allocating an addition array. The `BackgroundBaseColors` and the `BackgroundGrooveBaseColors` can then also be removed.

2024-11-08 02:36 UTC, EliteAsian123 commented on Assets/Script/Settings/Preview/FakeTrackPlayer.cs
> +            var currentColorProfile = CurrentGameModeInfo.FretColorProvider(colorProfile);
Is this addition intentional? I don't see the variable being used.

2024-11-11 00:20 UTC, EliteAsian123 commented on Assets/Script/Gameplay/Visuals/TrackMaterial.cs
> +            public static Preset FromColors(System.Drawing.Color[] colors)
For now, you can even just completely get rid of the `Layer` struct and replace those fields with colors. Once we add texture support, it's likely some other things in this class will have to be redone anyways, so removing it for now is fine!

2024-11-11 05:42 UTC, thomeval commented
Okay, PR is updated, ready for review.

2024-11-21 02:49 UTC, merged