Add option to sort by play count
YARC-Official/YARG pull request #931
Opened 2024-12-24 06:02 UTC by wyrdough

This PR adds a new sorting option to the song library to sort by play count.

When sorting by play count, two categories are displayed, played and unplayed. Played songs are sorted by the number of times played by the first connected profile, in descending order. Unplayed songs are sorted by whatever sort order was in use immediately prior to switching to play count order.

2024-12-24 21:41 UTC, sonicfind requested changes

2024-12-24 21:41 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +            var player = PlayerContainer.Players.First();
Could be a bot. Need a more full-proof method to determine this which would involve reworking `PlayerContainer` fundamentally.

2024-12-24 21:41 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +using System.Linq;
Please refrain from LINQ

2024-12-24 21:41 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +                zeroPlaySongs.AddRange(songs);
Please refrain from LINQ. We should always aim to dodge hidden allocations of enumerable containers.
```suggestion
                foreach (var song in category.Songs)
                {
                    if (!counts.Contains(song))
                    {
                        zeroPlaySongs.Add(song);
                    }
                }
```

2024-12-24 21:41 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +
You should follow the example of the `Playable` sort here. The point of `_playable` starting as null is to communicate to `GetPlayableSongs()` that it needs to regenerate the collection after a re-scan. See `FillContainers()`.

2024-12-24 21:41 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +            var player = PlayerContainer.Players.First();
Additionally, without checking for the prior state of the player used to determine the order, you'll end up needlessly re-generating the same list even when the player is the same. You need to keep track of the playerId last used to know whether the whole process actually needs to occur.

2024-12-24 21:41 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +            return countCategories;
You're not even using the `_sortPlayCounts` variable here to cache the result.

2024-12-24 21:41 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +            var player = PlayerContainer.Players.First();
OH, and the last pre-sort used too. There's a lot you need to track (and is generally why I opted to only ever use the name sort as the sub-sort).

That only gets *more* problematic when taking into account how playable sort works.

2024-12-25 10:20 UTC, wyrdough commented on Assets/Script/Song/SongContainer.cs
> +                zeroPlaySongs.AddRange(songs);
I get the concern in the game loop, but I do wonder why the use of LINQ is a problem in menus etc?

2024-12-26 09:03 UTC, wyrdough commented
Updated to remove _sortPlayCounts variable, deal properly with case where no profiles are connected or only bots are connected, and remove the use of Except to filter played songs from unplayed list.

I'm still using a LINQ expression to evaluate the connected profiles, as that is how it is done every other place in YARG that checks whether a non-bot profile is connected.

2025-01-01 02:11 UTC, sonicfind commented on Assets/Script/Song/SongContainer.cs
> +                zeroPlaySongs.AddRange(songs);
You already changed it but:

Whenever you perform some LINQ operation that creates a collection, especially within a loop, you add extra pressure on GC due to the collection that's generated behind the scenes. It may not seem like it's too important due to it being a menu, but GC may hold onto that collection for a while. That creates a higher likelihood that gameplay will halt from GC collecting that memory back.

2025-01-01 02:12 UTC, sonicfind commented
> I'm still using a LINQ expression to evaluate the connected profiles, as that is how it is done every other place in YARG that checks whether a non-bot profile is connected.

I'm cool with that. The only allocations there would be *maybe* the lambda (if that isn't inlined) and a stack allocated integer.

2025-01-06 22:13 UTC, EliteAsian123 requested changes
Hello!

In general, the queries to the databases are very slow, so it could hurt performance when sorting by play count. However, there's nothing you can really do about that at the moment, so it's fine for now.

Basically now just waiting for @sonicfind's approval, and we're good!

2025-01-06 22:13 UTC, EliteAsian123 commented on Assets/Script/Song/SongContainer.cs
> +                })(),
This syntax here is kinda hacky. It's probably just better to first, put this switch expression result into a variable, and set the default case to return `null`. Then, check to see if the result variable is `null`, and then put this code there. Return the result variable.

2025-01-06 22:13 UTC, EliteAsian123 commented on Assets/Script/Song/SongContainer.cs
> +            {
The `PlayerContainer.Players.Count(e => !e.Profile.IsBot) == 0` is reused a couple of times, so it should probably become a method within `PlayerContainer`.

2025-01-06 22:13 UTC, EliteAsian123 commented on Assets/Script/Scores/ScoreContainer.cs
> +                    songList.Add(list.Pick());
I'm pretty sure in this circumstance, all of the songs in the `out var list` should be added to the `songList`. This is because there won't be more than one element in the `out var list` when the "Allow Duplicate Songs" option is disabled. I may be wrong, but to me, that makes more sense here.

2025-01-18 21:02 UTC, merged